<?php
$page_name = "contato";
$page_title = "Contato";
$page_id = 9; // salvar na tabela página para gerar o ID

//URls
$url_listagem = BASE_ADMIN_URL . '/' . $page_name . '-lista.html';
$url_formulario = BASE_ADMIN_URL . '/' . $page_name . '-form.html';

$objeto = new Contato(true);

//Informações da Página para BreadCrumb
$pagina = new Pagina();
$pagina->setIdTable($page_id);
$pagina->getByCod();

$grupo = new Pagina();
$grupo->setIdTable($pagina->getIdParent());
$grupo->getByCod();
//End - Informações da Página para BreadCrumb

//Verifica se é alteração ou inclusão para carregar os dados
$id_registro = getRequest("id") ? getRequest("id") : 0;
if ($id_registro > 0) {
    $objeto->setIdTable($id_registro);
    $objeto->getByCod();
    $title = $pagina->getTitulo() . ": " . $id_registro . " | Painel Administrativo";
} else {
    $title = "Novo Registro | Painel Administrativo";
}

//Add JS e CSS
$str_add_css = array(
    'bootstrap-table',
    'switchery',
    'fontawesome',
    'bootstrap-colorpicker.min'
);
$str_add_js = array(
    'bootstrap-table',
    'switchery',
    'jquery.inputmask.bundle',
    'fontawesome',
    'bootstrap-confirmation.min',
    'bootstrap-colorpicker.min'
);

//BreadCrumb
$breadcrumb = array(
    array(
        "url" => BASE_ADMIN_URL,
        "nome" => ' Home',
        "icon" => '<i class="fas fa-home fontawesome"></i>'
    ),
    array(
        "url" => "#",
        "nome" => ' ' . $grupo->getTitulo(),
        "icon" => '<i class="fa ' . $grupo->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_listagem,
        "nome" => ' Todos ' . $pagina->getTitulo(),
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_formulario,
        "nome" => ' ' . $page_title,
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    )
);

//Add Header
include_once('gestao/header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <?php
            //Add BreadCrumb
            include_once('gestao/breadcrumb.phtml');
            ?>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <a href="<?php echo $url_listagem ?>" class="btn_admin btn btn-default"><i class="fa fa-undo" aria-hidden="true"></i> Voltar</a>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12">
                <?php
                $retorno = getRequest('msg');
                if ($retorno != "" && $retorno == "ok") {
                     ?>
                    <div class="alert alert-success">
                        <strong><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Ok...</strong> Os dados foram salvos com sucesso!
                    </div>
                    <?php
                } elseif ($retorno != "" && $retorno == "erro") {
                    ?>
                    <div class="alert alert-danger">
                        <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Houve algum problema ao salvar os dados, por favor tente novamente!
                    </div>
                    <?php
                }
                ?>
                <div class="clearfix"></div>
                <form name="form_admin" id="form_admin" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="acao" value="<?php echo $id_registro > 0 ? 'alterar' : 'incluir' ?>"/>
                    <input type="hidden" name="acao_posterior" id="acao_posterior" value="" />
                    <input type="hidden" name="ip_registro" id="ip_registro" value="<?php echo $objeto->getIpRegistro() ?>" />
                    <div class="row">
                        <div class="col-md-2 input_form">
                            <label for="id_registro">Código</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-hashtag" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" placeholder=""
                                       aria-describedby="id_registro" name="id_registro" id="id_registro"
                                       value="<?php echo $objeto->getIdTable() ?>" readonly="readonly"/>
                            </div>
                        </div>
                        <div class="col-md-4 input_form">
                            <label for="datahora_contato">Data/Hora do Contato</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                                <input type="text" class="form-control"
                                       aria-describedby="datahora_contato"
                                       name="datahora_contato" id="datahora_contato"
                                       value="<?php echo $objeto->getDatahoraContato() ?>"
                                       readonly/>
                            </div>
                        </div>
                        <div class="col-md-3 col-lg-2 input_form">
                            <label for="status">Status</label>
                            <div style="position:relative">
                                <div class="form-group">
                                    <input type="checkbox" id="status" name="status"
                                           <?php if ($objeto->getStatus() == "A" || $id_registro == '') { ?>checked="checked"<?php } ?>
                                           class="js-switch flag_form" value="A" data-active="Atendido"
                                           data-inactive="Pendente"/>
                                    <span class="label_flag"><?php echo $objeto->getStatus() == "A" || $id_registro == '' ? "Atendido" : "Pendente" ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-6 col-lg-3 input_form">
                            <label for="nome">Nome</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-user" aria-hidden="true"></i></span>
                                <input type="text" class="form-control"
                                       aria-describedby="nome"
                                       name="nome" id="nome"
                                       value="<?php echo $objeto->getNome() ?>"
                                       readonly/>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 input_form">
                            <label for="email">E-mail</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope-o" aria-hidden="true"></i></span>
                                <input type="email" class="form-control"
                                       aria-describedby="email"
                                       name="email" id="email"
                                       value="<?php echo $objeto->getEmail() ?>"
                                       readonly/>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 input_form">
                            <label for="telefone">Telefone</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-phone" aria-hidden="true"></i></span>
                                <input type="text" class="form-control"
                                       aria-describedby="telefone"
                                       name="telefone" id="telefone"
                                       value="<?php echo $objeto->getTelefone() ?>"
                                       readonly/>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 input_form">
                            <label for="celular">Celular</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-phone" aria-hidden="true"></i></span>
                                <input type="text" class="form-control"
                                       aria-describedby="celular"
                                       name="celular" id="celular"
                                       value="<?php echo $objeto->getCelular() ?>"
                                       readonly/>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-12 input_form">
                            <label for="mensagem">Mensagem</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-keyboard-o" aria-hidden="true"></i></span>
                                <textarea class="form-control" name="mensagem" id="mensagem" rows="5" readonly><?php echo $objeto->getMensagem() ?></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 text-right">
                            <div class="line-buttons">
                                <?php /*
                                if ($id_registro) {
                                    ?>
                                    <a href="#" class="btn btn-danger" data-toggle="confirmation_delete"
                                       data-title="Excluir Permanetemente?"
                                       data-content="Após confirmada está ação não pode ser desfeita!"><i
                                                class="fa fa-trash"></i> Excluir</a>
                                    <a href="#" class="btn btn-warning" data-toggle="confirmation_cancel"
                                       data-title="Deseja Realmente Cancelar?"
                                       data-content="Todas alterações não salvas serão perdidas."><i
                                                class="fa fa-ban"></i> Cancelar</a>
                                    <?php
                                }
                                */ ?>
                                <a href="#" class="btn btn-success btn_submit_form"><i class="fa fa-floppy-o"></i>
                                    Salvar</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<?php
//Add Footer
include_once('gestao/footer.phtml');