<script type="text/javascript" src="<?php echo ADMIN_JS_URL ?>/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo ADMIN_JS_URL ?>/fontawesome.js"></script>
<script type="text/javascript">
    var gestao_url = '<?php echo BASE_ADMIN_URL; ?>';
    var site_url = '<?php echo BASE_SITE_URL ?>';
    var site_uploads = '<?php echo UPLOADS_URL; ?>';
</script>
<?php
#adiciona caso exista arquivos js especificos
if (isset($str_add_js) && count($str_add_js) > 0) {
    foreach ($str_add_js as $new_file_js)
        print('<script type="text/javascript" src="' . ADMIN_JS_URL . '/' . $new_file_js . '.js"></script>' . chr(13));
}
?>
<script type="text/javascript" src="<?php echo ADMIN_JS_URL ?>/3dots.js"></script>