<?php
$page_name = "home";
$page_title = "Página Inicial";
$page_id = 1; // salvar na tabela página para gerar o ID

$obj_config = new Configuracao(true);
$title = "Painel Administrativo";
$str_add_css = array();
$str_add_js = array(/*"chart.min",
      "chart-data"*/);

//BreadCrumb
$breadcrumb = array(array("url" => BASE_ADMIN_URL,
    "nome" => ' Home',
    "icon" => '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'));

//Add Header
include_once('header.phtml');
?>
    <div  class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" >
        <div class="row">
            <?php
            //Add BreadCrumb
            include_once('breadcrumb.phtml');
            ?>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
        </div>
        <?php
        echo 'Painel administrativo';

            ?>
        
        <?php if (getRequest('permissao')) { ?>
            <div class="clearfix"></div>
            <br/>
            <div class="alert alert-danger">
                <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Desculpe, você não possui permissão para executar esta determinada função, por favor tente novamente!
            </div>
        <?php } ?>
    </div>
    <script>
        $(document).ready(function () {
            $(".add_my_ip").on("click", function () {
                $("#liberar_ip").val($(this).attr("id"));
            });
        });
    </script>
<?php
//Add Footer
include_once('footer.phtml');
