<?php
$page_name = "institucionais";
$page_title = "Institucionais";
$page_id = 16; // salvar na tabela página para gerar o ID

//URls
$url_listagem = BASE_ADMIN_URL . '/' . $page_name . '-lista.html';
$url_formulario = BASE_ADMIN_URL . '/' . $page_name . '-form.html';

$objeto = new Institucional(true);

$tab = getRequest('tab') ? (int)getRequest('tab') : 1;

//Informações da Página para BreadCrumb
$pagina = new Pagina();
$pagina->setIdTable($page_id);
$pagina->getByCod();

$grupo = new Pagina();
$grupo->setIdTable($pagina->getIdParent());
$grupo->getByCod();
//End - Informações da Página para BreadCrumb

//Verifica se é alteração ou inclusão para carregar os dados
$id_registro = getRequest("id") ? getRequest("id") : 0;
if ($id_registro > 0) {
    $objeto->setIdTable($id_registro);
    $objeto->getByCod();
    $title = $pagina->getTitulo() . ": " . $id_registro . " | Painel Administrativo";
} else {
    $title = "Novo Registro | Painel Administrativo";
}

//Add JS e CSS
$str_add_css = array(
    'bootstrap-table',
    'switchery',
    'bootstrap-colorpicker.min',
);
$str_add_js = array(
    'bootstrap-table',
    'switchery',
    'tinymce2/tinymce.min',
    'jquery.inputmask.bundle',
    'bootstrap-confirmation.min',
    'bootstrap-colorpicker.min'
);

//BreadCrumb
$breadcrumb = array(
    array(
        "url" => BASE_ADMIN_URL,
        "nome" => ' Home',
        "icon" => '<i class="fas fa-home fontawesome"></i>'
    ),
    array(
        "url" => "#",
        "nome" => ' ' . $grupo->getTitulo(),
        "icon" => '<i class="fa ' . $grupo->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_listagem,
        "nome" => ' Todos ' . $pagina->getTitulo(),
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_formulario,
        "nome" => ' ' . $page_title,
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    )
);

//Add Header
include_once('gestao/header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <?php
                //Add BreadCrumb
                include_once('gestao/breadcrumb.phtml');
            ?>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <a href="<?php echo $url_listagem ?>" class="btn_admin btn btn-default">
                    <i class="fa fa-undo" aria-hidden="true"></i>
                    Voltar</a>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12">
                <?php
                    $retorno = getRequest('msg');
                    if ($retorno != "" && $retorno == "ok") {
                        ?>
                        <div class="alert alert-success">
                            <strong><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Ok...</strong> Os dados foram
                            salvos com sucesso!
                        </div>
                        <?php
                    } elseif ($retorno != "" && $retorno == "erro") {
                        ?>
                        <div class="alert alert-danger">
                            <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Houve algum
                            problema ao salvar os dados, por favor tente novamente!
                        </div>
                        <?php
                    }
                ?>
                <div class="clearfix"></div>
                <?php
                    // ID 2 = Perguntas Frequentes
                    if ($id_registro == 2) {
                        ?>
                        <div class="tabs">
                            <ul class="nav nav-pills">
                                <li <?php if ($tab == 1) {?>class="active"<?php } ?>><a href="#tab_institucional" data-toggle="tab">Institucional</a></li>
                                <li <?php if ($tab == 2) {?>class="active"<?php } ?>><a href="#tab_complemento" data-toggle="tab">Complementos</a></li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade in <?php if ($tab == 1) {?>active<?php } ?>" id="tab_institucional">
                                    <?php include_once "institucionais.phtml" ?>
                                </div>
                                <div class="tab-pane fade in <?php if ($tab == 2) {?>active<?php } ?>" id="tab_complemento">
                                    <?php include_once "complementos.phtml" ?>
                                </div>
                            </div>
                        </div>
                        <?php
                    } else {
                        include_once "institucionais.phtml";
                    }
                ?>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            // Confirma o cancelamento
            $('[data-toggle=confirmation_cancel]').confirmation({
                rootSelector: '[data-toggle=confirmation_cancel]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim',
                        onClick: function () {
                            location.reload();
                        }
                    }
                ]
            });

            // Apagar Complemento
            $(document).on("click", "#complementos span.apagarComplemento", function () {
                if (confirm("Deseja realmente apagar este item?")) {
                    $.ajax({
                        method: "POST",
                        url: gestao_url + "/institucionais-form.html?id=" + $("#id_institucional").val(),
                        data: {
                            acao: "removerComplemento",
                            id_complemento: $(this).attr('data-id-complemento'),
                            id_registro: $("#id_institucional").val()
                        },
                        success: function (resposta) {
                            window.location = "<?php echo $url_formulario ?>?id=" + $("#id_institucional").val() + "&tab=2";
                        }
                    });
                }
            });
        });
    </script>
<?php
//Add Footer
include_once('gestao/footer.phtml');