<?php
$page_name = "textos";
$page_title = "Textos";
$page_id = 16; // salvar na tabela página para gerar o ID

//URls
$url_listagem = BASE_ADMIN_URL . '/' . $page_name . '-lista.html';
$url_formulario = BASE_ADMIN_URL . '/' . $page_name . '-form.html';

$objeto = new Texto(true);

//Informações da Página para BreadCrumb
$pagina = new Pagina();
$pagina->setIdTable($page_id);
$pagina->getByCod();

$grupo = new Pagina();
$grupo->setIdTable($pagina->getIdParent());
$grupo->getByCod();
//End - Informações da Página para BreadCrumb

//Verifica se é alteração ou inclusão para carregar os dados
$id_registro = getRequest("id") ? getRequest("id") : 0;
if ($id_registro > 0) {
    $objeto->setIdTable($id_registro);
    $objeto->getByCod();
    $title = $pagina->getTitulo() . ": " . $id_registro . " | Painel Administrativo";
    $fotos = new TextoFoto();
    $imagens = $fotos->getFotosEnviadas($id_registro);
} else {
    $title = "Novo Registro | Painel Administrativo";
}

//Add JS e CSS
$str_add_css = array('bootstrap-table',
    'switchery',
    'dropzone',
    'bootstrap-colorpicker.min');
$str_add_js = array('bootstrap-table',
    'switchery',
    'jquery.inputmask.bundle',
    'bootstrap-confirmation.min',
    'tinymce2/tinymce.min',
    'dropzone',
    'uploads_textos',
    'bootstrap-colorpicker.min');

//BreadCrumb
$breadcrumb = array(array("url" => BASE_ADMIN_URL,
    "nome" => ' Home',
    "icon" => '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'),
    array("url" => "#",
        "nome" => ' ' . $grupo->getTitulo(),
        "icon" => '<i class="fa ' . $grupo->getIcone() . '" aria-hidden="true"></i>'),
    array("url" => $url_listagem,
        "nome" => ' Todos ' . $pagina->getTitulo(),
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'),
    array("url" => $url_formulario,
        "nome" => ' ' . $page_title,
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'));

//Add Header
include_once('gestao/header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <?php
            //Add BreadCrumb
            include_once('gestao/breadcrumb.phtml');
            ?>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <a href="<?php echo $url_listagem ?>" class="btn_admin btn btn-default"><i class="fa fa-undo"
                                                                                           aria-hidden="true"></i>
                    Voltar</a>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12">
                <?php
                $retorno = getRequest('msg');
                if ($retorno != "" && $retorno == "ok") {
                    ?>
                    <div class="alert alert-success">
                        <strong><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Ok...</strong> Os dados foram
                        salvos com sucesso!
                    </div>
                    <?php
                } elseif ($retorno != "" && $retorno == "erro") {
                    ?>
                    <div class="alert alert-danger">
                        <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Houve algum
                        problema ao salvar os dados, por favor tente novamente!
                    </div>
                    <?php
                }
                ?>
                <div class="clearfix"></div>
                <form name="form_admin" id="form_admin" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="acao" value="<?php echo $id_registro > 0 ? 'alterar' : 'incluir' ?>"/>
                    <input type="hidden" name="acao_posterior" id="acao_posterior" value=""/>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-xs-12 col-md-2 input_form">
                                    <label for="id_registro">código</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-hashtag" aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" placeholder=""
                                               aria-describedby="id_registro" name="id_registro" id="id_registro"
                                               value="<?php echo $objeto->getIdTable() ?>" readonly="readonly"/>
                                    </div>
                                </div>
                                <div class="col-lg-1 col-md-6 input_form">
                                    <label for="status">status</label>
                                    <div style="position:relative">
                                        <div class="form-group">
                                            <input type="checkbox" id="status" name="status"
                                                   <?php if ($objeto->getStatus() == "A") { ?>checked="checked"<?php } ?>
                                                   class="js-switch flag_form" value="A" data-active="Ativo"
                                                   data-inactive="Inativo"/>
                                            <span class="label_flag"><?php echo $objeto->getStatus() == "A" ? "Ativo" : "Inativo" ?></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-xs-12 col-md-4 input_form">
                                    <label for="meta_title">meta título</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" placeholder=""
                                               aria-describedby="meta_title" name="meta_title" id="meta_title"
                                               required="required" data-error="o campo meta título está vázio."
                                               value="<?php echo $objeto->getMetaTitle() ?>"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-lg-5 input_form">
                                    <label for="meta_description">meta descrição</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" placeholder=""
                                               aria-describedby="meta_description" name="meta_description"
                                               id="meta_description"
                                               value="<?php echo $objeto->getMetaDescription() ?>"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-lg-3 input_form">
                                    <label for="meta_keywords">palavras chaves</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-key"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" placeholder=""
                                               aria-describedby="meta_keywords" name="meta_keywords" id="meta_keywords"
                                               value="<?php echo $objeto->getMetaKeywords() ?>"/>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-xs-12 col-md-6 input_form">
                                    <label for="nome">nome</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" placeholder="" aria-describedby="nome"
                                               name="nome" id="nome" required="required"
                                               data-error="o campo nome está vázio."
                                               value="<?php echo $objeto->getNome() ?>"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-md-6 input_form">
                                    <label for="titulo">título</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" placeholder="" aria-describedby="titulo"
                                               name="titulo" id="titulo" value="<?php echo $objeto->getTitulo() ?>"
                                               required="required" data-error="o campo título está vázio."/>
                                    </div>
                                </div>
                                <?php if ($id_registro != SITE_TEXTO_POLITICA){?>
                                <div class="col-xs-12 col-md-12 input_form">
                                    <label for="subtitulo">subtítulo</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" placeholder=""
                                               aria-describedby="subtitulo" name="subtitulo" id="subtitulo"
                                               value="<?php echo $objeto->getSubtitulo() ?>"/>
                                    </div>
                                </div>
                                <?php }?>
                                <div class="clearfix"></div>
                                <div class="col-lg-12 input_form">
                                    <label for="descricao">descrição</label>
                                    <textarea class="tinymce" id="descricao"
                                              name="descricao"><?php echo $objeto->getDescricao() ?></textarea>
                                </div>
                                <?php
                                if ($id_registro > 0 && $id_registro == SITE_TEXTO_SOBRE) {
                                    ?>
                                    <div class="col-xs-12 col-md-4 input_form">
                                        <label for="missao">missão</label>
                                        <textarea name="missao" id="missao" rows="5"
                                                  class="form-control"><?php echo $objeto->getMissao() ?></textarea>
                                    </div>
                                    <div class="col-xs-12 col-md-4 input_form">
                                        <label for="visao">visão</label>
                                        <textarea name="visao" id="visao" rows="5"
                                                  class="form-control"><?php echo $objeto->getVisao() ?></textarea>
                                    </div>
                                    <div class="col-xs-12 col-md-4 input_form">
                                        <label for="valores">valores</label>
                                        <textarea name="valores" id="valores" rows="5"
                                                  class="form-control"><?php echo $objeto->getValores() ?></textarea>
                                    </div>
                                    <?php
                                }
                                ?>
                                <div class="clearfix"></div>
                                <?php
                                if ($id_registro > 0 && $id_registro == SITE_TEXTO_PERGUNTAS_FREQUENTES) {
                                    ?>
                                    <div class="col-lg-8 input_form">
                                        <label for="url_imagem_home">imagem da home: 960px x 960px</label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-picture-o"
                                                                               aria-hidden="true"></i></span>
                                            <input type="file" class="form-control" placeholder=""
                                                   aria-describedby="url_imagem_home" name="url_imagem_home"
                                                   id="url_imagem_home"/>
                                        </div>
                                        <?php
                                        if ($objeto->getUrlImagemHome()) {
                                            ?>
                                            <div class="box_imagem_admin">
                                                <span class="apagar-imagem" data-imagem-home="true" data-id-texto="<?php echo (isset($id_registro)) ? $id_registro : 0; ?>">apagar imagem</span>
                                                <img src="<?php echo UPLOADS_URL . '/textos/' . $objeto->getUrlImagemHome() ?>"
                                                     alt="" style="padding-top:5px" width="100%"/>
                                            </div>
                                            <?php
                                        }
                                        ?>
                                    </div>
                                    <?php
                                }
                                ?>
                                <div class="col-lg-6 input_form">
                                    <label for="url_imagem">imagem: 1920px x 500px</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-picture-o"
                                                                           aria-hidden="true"></i></span>
                                        <input type="file" class="form-control" placeholder=""
                                               aria-describedby="url_imagem" name="url_imagem" id="url_imagem"/>
                                    </div>
                                    <?php
                                    if ($objeto->getUrlImagem()) {
                                        ?>
                                        <div class="box_imagem_admin">
                                            <span class="apagar-imagem" data-imagem-home="false" data-id-texto="<?php echo (isset($id_registro)) ? $id_registro : 0; ?>">apagar imagem</span>
                                            <img src="<?php echo UPLOADS_URL . '/textos/' . $objeto->getUrlImagem() ?>"
                                                 alt="" style="padding-top:5px" width="100%"/>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                </div>

                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 text-right">
                            <div class="line-buttons">
                                <?php
                                if ($id_registro) {
                                    ?>
                                    <a href="#" class="btn btn-danger" data-toggle="confirmation_delete"
                                       data-title="Excluir Permanetemente?"
                                       data-content="Após confirmada está ação não pode ser desfeita!"><i
                                                class="fa fa-trash"></i> Excluir</a>
                                    <a href="#" class="btn btn-warning" data-toggle="confirmation_cancel"
                                       data-title="Deseja Realmente Cancelar?"
                                       data-content="Todas alterações não salvas serão perdidas."><i
                                                class="fa fa-ban"></i> Cancelar</a>
                                    <?php
                                }
                                ?>
                                <a href="#" class="btn btn-primary btn_submit_form_new"><i class="fa fa-floppy-o"></i>
                                    Salvar e Adicionar Outro</a>
                                <a href="#" class="btn btn-success btn_submit_form"><i class="fa fa-floppy-o"></i>
                                    Salvar</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <?php if ($id_registro > 0 && $id_registro == SITE_TEXTO_SOBRE) { ?>
                <div class="col-md-12">
                    <h2 class="subtitulo">Fotos</h2>
                </div>
                <div class="clear"></div>
                <div class="col-md-12">
                    <form action="<?php echo $url_formulario ?>" class="dropzone" enctype="multipart/form-data"
                          data-form="form-imagem">
                        <input type="hidden" name="acao" id="acao" value="upload"/>
                        <input type="hidden" name="id_registro" id="id_registro" value="<?php echo $id_registro; ?>"/>
                    </form>
                </div>
                <div class="clear"></div>
                <div class="col-md-12">
                    <h2 class="subtitulo">Imagens Enviadas</h2>
                </div>
                <div id="imagens-upload" class="col-md-12">
                    <div class="loading">
                        <div class="loader">Loading...</div>
                    </div>
                    <?php
                    if ($imagens != "") {
                        foreach ($imagens as $imagem) {
                            ?>
                            <div class="container-img">
                                <div class="img">
                                    <img src="<?php echo UPLOADS_URL . '/textos/album/medias/' . $imagem->url_imagem; ?>"
                                         alt="">
                                </div>
                                <span class="apagar"
                                      data_id_objeto_foto="<?php echo $imagem->id_texto_foto; ?>">Apagar</span>
                            </div>
                            <?php
                        }
                    } else {
                        echo "Sem imagens no momento!";
                    }
                    ?>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            <?php } ?>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $(".apagar-imagem").on("click", function () {
                var campo = "url_imagem";
                if($(this).attr("data-imagem-home") == "true") {
                    campo = "url_imagem_home";
                }
                var id_texto = $(this).attr("data-id-texto");
                var este = $(this);
                if (typeof id_texto != "undefined" && id_texto > 0) {
                    if (confirm("Deseja realmente apagar esta imagem?")) {
                        $.ajax({
                            url: window.location.href,
                            method: 'post',
                            data: {
                                acao: 'apagar-imagem-texto',
                                campo: campo,
                                id_texto: id_texto
                            },
                            dataType: "json",
                            success: function (response) {
                                if (response == 1) {
                                    este.parent().find("img").fadeOut(500);
                                }
                                else {
                                    alert('Houve um problema, tente novamente mais tarde!');
                                }
                            }
                        })
                    }
                }

            });
            $('.mask_time').inputmask("99:99"); //mask hora

            if ($('#cp_menu').length > 0) {
                $('#cp_menu').colorpicker();
            }

            //Checkbox personalizado
            $('#restricoes_horarios').change(function () {
                if (this.checked) {
                    $('div.horarios_restritos').slideDown();
                } else {
                    $('div.horarios_restritos').slideUp();
                }
            });

            //Confirma a exclusão
            $('[data-toggle=confirmation_delete]').confirmation({
                rootSelector: '[data-toggle=confirmation_delete]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim, Excluir!',
                        onClick: function () {
                            var codigo = $('#id_registro').val();
                            $.ajax({
                                method: "POST",
                                url: "<?php echo $url_formulario ?>",
                                data: {
                                    'acao': 'excluir',
                                    'id': codigo
                                },
                                success: function (retorno) {
                                    if (retorno == 'ok') {
                                        window.location = '<?php echo $url_listagem ?>?del=ok';
                                    }
                                }
                            });
                            return false;
                        }
                    }
                ]
            });


            //Confirma o cancelamento
            $('[data-toggle=confirmation_cancel]').confirmation({
                rootSelector: '[data-toggle=confirmation_cancel]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim',
                        onClick: function () {
                            location.reload();
                        }
                    }
                ]
            });
        });
    </script>
<?php
//Add Footer
include_once('gestao/footer.phtml');