<head>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_CSS_URL ?>/innovare.min.css"/>
</head>
<div class="row fullContainer" id="manutencao">
    <div class="medium-6 large-6 columns medium-centered large-centered text-center">
        <div class="container">
            <h1>
                <img src="<?php echo UPLOADS_URL . "/tema/" . SITE_LOGOTIPO; ?>" alt="<?php echo SITE_TITLE ?>">
            </h1>
            <h2>SITE EM MANUTENÇÃO</h2>
            Desculpe! Estamos em Manutenção , por favor tente mais tarde!
        </div>
    </div>
</div>