<?php
$page_back = "";
$page_id = "nosso-servico-detalhes";

$str_add_css = array();
$str_add_js = array();

$texto = new Texto();
$textos = $texto;
$textos->setIdTable(SITE_TEXTO_MIGRAR_MINHA_EMPRESA);
$textos->getByCod();

$obj_servico = new Servico();
$servico = $obj_servico;
$servico->setIdTable(getRequest("id_nosso_servico"));
$servico->getByCod();

include_once("header.phtml");
if ($servico->url_banner != "") {
    ?>
    <div class="row fullWidth" id="banner">
        <img src="<?php echo UPLOADS_URL . "/servicos/banners/" . $servico->url_banner ?>" alt="<?php echo SITE_TITLE ?>">
    </div>
    <?php
}
?>
    <div class="row fullContainer" id="breadcrumb">
        <div class="columns">
            <a href="<?php echo BASE_SITE_URL; ?>">Home</a> | <span><?php echo $servico->nome_servico;?></span>
            <h1 class="titulo"><?php echo $servico->nome_servico; ?></h1>
        </div>
    </div>
    <div class="row fullContainer" id="conteudo-informacoes">
        <div class="columns">
            <?php echo $servico->descricao_servico; ?>
        </div>
        <div class="columns" id="buttom">
            <a href="<?php echo BASE_SITE_URL ?>/contato">
                <div>Entre em contato</div>
            </a>
        </div>
    </div>
<?php
include_once("footer.phtml");
?>