<?php
$page_back = "";
$page_id = "parceiros";

$str_add_css = array();
$str_add_js = array();

$texto = new Texto();
$obj_parceiro = new Parceiro();

$textos = $texto;
$textos->setIdTable(SITE_TEXTO_PARCEIROS);
$textos->getByCod();

$parceiros = $obj_parceiro->listAll("A", "posicao");

include_once("header.phtml");
if ($textos->url_imagem != "") {
    ?>
    <div class="row fullWidth" id="banner">
        <img src="<?php echo UPLOADS_URL . "/textos/" . $textos->url_imagem; ?>" alt="<?php echo SITE_TITLE ?>">
    </div>
    <?php
}
?>
    <div class="row fullContainer" id="breadcrumb">
        <div class="columns">
            <a href="<?php echo BASE_SITE_URL; ?>">Home</a> | <span>nossos parceiros</span>
            <h1 class="titulo"><?php echo $textos->titulo; ?></h1>
            <div class="texto"><?php echo $textos->subtitulo; ?></div>
        </div>
    </div>
    <div class="row fullContainer" id="info">
        <?php
        foreach ($parceiros as $parceiro) {
            ?>
            <div class="columns imagem end">
                <a <?php echo ($parceiro->link_parceiro != "#") ? 'href="' . $parceiro->link_parceiro . '"' : '' ?>
                        target="_blank">
                    <img src="<?php echo UPLOADS_URL . "/parceiros/" . $parceiro->imagem_parceiro; ?>"
                         alt="<?php echo $parceiro->nome_parceiro; ?>">
                </a>
            </div>
            <?php
        }
        ?>
    </div>
<?php
include_once("footer.phtml");
?>