<?php
    $page_name = "perfis";
    $page_title = "Manutenção de Perfis";
    $page_id = 2; // salvar na tabela página para gerar o ID
    
    //URls
    $url_listagem   =  BASE_ADMIN_URL.'/'.$page_name.'-lista.html';
    $url_formulario =  BASE_ADMIN_URL.'/'.$page_name.'-form.html';
    
    $objeto = new Perfil(true);
    
    //Informações da Página para BreadCrumb
    $pagina = new Pagina();
    $pagina->setIdTable($page_id);
    $pagina->getByCod();
    
    $grupo = new Pagina();
    $grupo->setIdTable($pagina->getIdParent());
    $grupo->getByCod();
    //End - Informações da Página para BreadCrumb
    
    //Verifica se é alteração ou inclusão para carregar os dados
    $id_registro = getRequest("id");
    if ($id_registro > 0) {
        $objeto->setIdTable($id_registro);
        $objeto->getByCod();
        $title = $pagina->getTitulo().": ".$id_registro." | Painel Administrativo";
    } else {
        $title = "Novo Registro | Painel Administrativo";
    }
    
    //Add JS e CSS
    $str_add_css = array(
        'bootstrap-table',
        'switchery'
    );
    $str_add_js = array(
        'bootstrap-table',
        'switchery',
        'bootstrap-confirmation.min'
    );
    
    //BreadCrumb
    $breadcrumb = array(
        array(
            "url" => BASE_ADMIN_URL,
            "nome" => ' Home',
            "icon" => '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'
        ),
        array(
            "url" => "#",
            "nome" => ' '.$grupo->getTitulo(),
            "icon" => '<i class="fa '.$grupo->getIcone().'" aria-hidden="true"></i>'
        ),
        array(
            "url" => $url_listagem,
            "nome" => ' Todos '.$pagina->getTitulo(),
            "icon" => '<i class="fa '.$pagina->getIcone().'" aria-hidden="true"></i>'
        ),
        array(
            "url" => $url_formulario,
            "nome" => ' '.$page_title,
            "icon" => '<i class="fa '.$pagina->getIcone().'" aria-hidden="true"></i>'
        )
    );
    
    //Add Header
    include_once('gestao/header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
        <?php
            //Add BreadCrumb
            include_once('gestao/breadcrumb.phtml');
        ?>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <a href="<?php echo $url_listagem ?>" class="btn_admin btn btn-default"><i class="fa fa-undo" aria-hidden="true"></i> Voltar</a>
            </div>
            <div class="col-lg-12">
                <?php
                    $retorno = getRequest('msg');
                    if ($retorno != "" && $retorno == "ok") {
                ?>
                <div class="alert alert-success">
                    <strong><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Ok...</strong> Os dados foram salvos com sucesso!
                </div>
                <?php
                    } elseif ($retorno != "" && $retorno == "erro") {
                ?>
                <div class="alert alert-danger">
                    <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Houve algum problema ao salvar os dados, por favor tente novamente!
                </div>
                <?php
                    }
                ?>
                <form name="form_admin" id="form_admin" method="post">
                <input type="hidden" name="acao" value="<?php echo $id_registro > 0 ? 'alterar' : 'incluir' ?>" />
                <input type="hidden" name="acao_posterior" id="acao_posterior" value="" />
                <div class="row">
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="col-lg-4 col-md-6 col-sm-8 input_form">
                                <label for="id_registro">código</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-hashtag" aria-hidden="true"></i></span>
                                    <input type="text" class="form-control" placeholder="" aria-describedby="id_registro" name="id_registro" id="id_registro" value="<?php echo $objeto->getIdTable() ?>" readonly="readonly" />
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 input_form">
                                <label for="nome">nome</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-align-left" aria-hidden="true"></i></span>
                                    <input type="text" class="form-control" placeholder="" aria-describedby="nome" name="nome" id="nome" value="<?php echo $objeto->getNome() ?>" required="required" data-error="Preencha este campo corretamente" />
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-6 input_form">
                                <label for="status">status</label>
                                <div style="position:relative">
                                    <div class="form-group">
                                        <input type="checkbox" id="status" name="status" <?php if ($objeto->getStatus() == "A") { ?>checked="checked"<?php } ?> class="js-switch flag_form" value="A" data-active="Ativo" data-inactive="Inativo" /> <span class="label_flag">Ativo</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <fieldset>
                            <legend>Condições de Restrição</legend>
                            <table class="table_check">
                                <tr>
                                    <th>Nome da Página</th>
                                    <th class="text-center" width="80">Visualizar</th>
                                    <th class="text-center" width="80">Incluir</th>
                                    <th class="text-center" width="80">Alterar</th>
                                    <th class="text-center" width="80">Excluir</th>
                                    <th class="text-center" width="80">Total</th>
                                </tr>
                                <?php
                                    $paginas = new Pagina();
                                    $lista_grupos = $paginas->getPaginas(0);
                                    if ($lista_grupos !== false) {
                                        $i=0;
                                        foreach($lista_grupos as $dados_grupo) {
                                            $color_line = ($i%2==0 ? '' : '#FFF');
                                            $i++;
                                            
                                            $lista_paginas = $paginas->getPaginas($dados_grupo->id_pagina);
                                            if ($lista_paginas !== false) {
                                ?>
                                <tr style="background-color:<?php echo $color_line ?>">
                                    <td colspan="6"><strong><?php echo $dados_grupo->titulo ?></strong></td>
                                </tr>
                                <?php           foreach($lista_paginas as $dados_pagina) {
                                                    $color_line = ($i%2==0 ? '' : '#FFF');
                                                    $i++;
                                                    
                                                    $visualizar = Perfil::verificaPermissao($id_registro, $dados_pagina->id_pagina, 'visualizar');
                                                    $incluir = Perfil::verificaPermissao($id_registro, $dados_pagina->id_pagina, 'incluir');
                                                    $alterar = Perfil::verificaPermissao($id_registro, $dados_pagina->id_pagina, 'alterar');
                                                    $excluir = Perfil::verificaPermissao($id_registro, $dados_pagina->id_pagina, 'excluir');            
                                ?>
                                <tr style="background-color:<?php echo $color_line ?>">
                                    <td style="padding-left:20px;white-space:nowrap">- <?php echo $dados_pagina->titulo ?></td>
                                    <td class="text-center"><label><input type="checkbox" name="visualizar[<?php echo $dados_pagina->id_pagina ?>]" id="visualizar_<?php echo $dados_pagina->id_pagina ?>" value="S" class="ckeck_permissao" <?php if ($visualizar) { ?>checked="checked"<?php }?> /></label></td>
                                    <td class="text-center"><label><input type="checkbox" name="incluir[<?php echo $dados_pagina->id_pagina ?>]" id="incluir_<?php echo $dados_pagina->id_pagina ?>" value="S" class="ckeck_permissao" <?php if ($incluir) { ?>checked="checked"<?php }?> /></label></td>
                                    <td class="text-center"><label><input type="checkbox" name="alterar[<?php echo $dados_pagina->id_pagina ?>]" id="alterar_<?php echo $dados_pagina->id_pagina ?>" value="S" class="ckeck_permissao" <?php if ($alterar) { ?>checked="checked"<?php }?> /></label></td>
                                    <td class="text-center"><label><input type="checkbox" name="excluir[<?php echo $dados_pagina->id_pagina ?>]" id="excluir_<?php echo $dados_pagina->id_pagina ?>" value="S" class="ckeck_permissao" <?php if ($excluir) { ?>checked="checked"<?php }?> /></label></td>
                                    <td class="text-center"><label><input type="checkbox" name="total[<?php echo $dados_pagina->id_pagina ?>]" id="total_<?php echo $dados_pagina->id_pagina ?>" value="S" class="check_todos" <?php if ($visualizar && $incluir && $alterar && $excluir) { ?>checked="checked"<?php }?> /></label></td>
                                </tr>
                                <?php           }
                                            }
                                        }
                                    }
                                ?>
                            </table>
                        </fieldset>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 text-right">
                        <div class="line-buttons">
                            <?php
                            if ($id_registro) {
                                ?>
                                <a href="#" class="btn btn-danger" data-toggle="confirmation_delete" data-title="Excluir Permanetemente?" data-content="Após confirmada está ação não pode ser desfeita!"><i class="fa fa-trash"></i> Excluir</a>
                                <a href="#" class="btn btn-warning" data-toggle="confirmation_cancel" data-title="Deseja Realmente Cancelar?" data-content="Todas alterações não salvas serão perdidas."><i class="fa fa-ban"></i> Cancelar</a>
                                <?php
                            }
                            ?>
                            <a href="#" class="btn btn-primary btn_submit_form_new"><i class="fa fa-floppy-o"></i> Salvar e Adicionar Outro</a>
                            <a href="#" class="btn btn-success btn_submit_form"><i class="fa fa-floppy-o"></i> Salvar</a>
                        </div>
                    </div>
                </div>
                </form>
            </div>
        </div>
        
    </div>
    <script>
        $(document).ready(function(){
            $('.check_todos').change(function(){
                if ($(this).is(":checked")) {
                    $(this).closest('tr').find('.ckeck_permissao').each(function(){
                        $(this).prop('checked', true);
                    });
                } else {
                    $(this).closest('tr').find('.ckeck_permissao').each(function(){
                        $(this).prop('checked', false);
                    });
                }
            });
            
            //Confirma a exclusão
            $('[data-toggle=confirmation_delete]').confirmation({
                rootSelector: '[data-toggle=confirmation_delete]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function() {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label:'Sim, Excluir!',
                        onClick: function() {
                            var codigo = $('#id_registro').val();
                            $.ajax({
                                method: "POST",
                                url: "<?php echo $url_formulario ?>",
                                data: { 
                                    'acao': 'excluir',
                                    'id': codigo
                                },
                                success: function(retorno) {
                                    if (retorno == 'ok') {
                                        window.location = '<?php echo $url_listagem ?>?del=ok';
                                    }
                                },
                                error: function(err) {
                                    console.log(err);
                                }
                            });
                            return false;
                        }
                    }
                ]
            });
            
            
            //Confirma o cancelamento
            $('[data-toggle=confirmation_cancel]').confirmation({
                rootSelector: '[data-toggle=confirmation_cancel]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function() {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label:'Sim',
                        onClick: function() {
                            location.reload();
                        }
                    }
                ]
            });
        });
    </script>
<?php
    //Add Footer
    include_once('gestao/footer.phtml');