<?php
$page_name = "configuracoes";
$page_title = "Configurações do Site";
$page_id = 5; // salvar na tabela página para gerar o ID

//URls
$url_listagem = BASE_ADMIN_URL . '/' . $page_name . '-lista.html';
$url_formulario = BASE_ADMIN_URL . '/' . $page_name . '-form.html';

$objeto = new Configuracao(true);

//Informações da Página para BreadCrumb
$pagina = new Pagina();
$pagina->setIdTable($page_id);
$pagina->getByCod();

$grupo = new Pagina();
$grupo->setIdTable($pagina->getIdParent());
$grupo->getByCod();
//End - Informações da Página para BreadCrumb

//Verifica se é alteração ou inclusão para carregar os dados
$title = "Configurações | Painel Administrativo";

//Add JS e CSS
$str_add_css = array(
    'bootstrap-table',
    'bootstrap-wysiwyg'
);
$str_add_js = array(
    'tinymce2/tinymce.min',
    'bootstrap-colorpicker.min',
    'bootstrap-confirmation.min',
    'jquery.mask.min'
);

//BreadCrumb
$breadcrumb = array(
    array(
        "url" => BASE_ADMIN_URL,
        "nome" => ' Home',
        "icon" => '<i class="fas fa-home fontawesome"></i>'
    ),
    array(
        "url" => "#",
        "nome" => ' ' . $grupo->getTitulo(),
        "icon" => '<i class="fa ' . $grupo->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_listagem,
        "nome" => ' ' . $page_title,
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    )
);

//Add Header
include_once('gestao/header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <?php
        //Add BreadCrumb
        include_once('gestao/breadcrumb.phtml');
        ?>
    </div>
    <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8">
        <h1 class="page-header"><?php echo $page_title ?></h1>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 text-right">
        <a href="<?php echo $url_listagem ?>" class="btn_admin btn btn-default"><i class="fa fa-undo" aria-hidden="true"></i> Voltar</a>
    </div>
    <div class="clearfix"></div>
    <div class="col-lg-12">
        <?php
        $retorno = getRequest('msg');
        if ($retorno != "" && $retorno == "ok") {
            ?>
            <div class="alert alert-success">
                <strong><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Ok...</strong> Os dados foram salvos com sucesso!
            </div>
            <?php
        } elseif ($retorno != "" && $retorno == "erro") {
            ?>
            <div class="alert alert-danger">
                <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Houve algum problema ao salvar os dados, por favor tente novamente!
            </div>
            <?php
        }
        ?>
        <div class="clearfix"></div>
        <div class="tabs">
            <ul class="nav nav-pills">
                <li class="active"><a href="#tab_gerais" data-toggle="tab">Configurações Gerais</a></li>
                <li><a href="#tab_seo" data-toggle="tab">SEO</a></li>
                <li><a href="#tab_tema" data-toggle="tab">Tema</a></li>
                <li><a href="#tab_sociais" data-toggle="tab">Redes Sociais</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade in active" id="tab_gerais">
                    <form name="form_admin" id="form_admin" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="acao" value="alterar"/>
                        <div class="row">
                            <div class="col-md-6 input_form">
                                <label for="SITE_TELEFONE">Telefone:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                                    <input type="tel" class="form-control" placeholder="" aria-describedby="SITE_TELEFONE" name="SITE_TELEFONE" id="SITE_TELEFONE" value="<?php echo SITE_TELEFONE; ?>" onkeydown="maskTelephone(this, false);"
                                           onkeyup="maskTelephone(this, false);" onblur="maskTelephone(this, true);"/>
                                </div>
                            </div>
                            <div class="col-md-6 input_form">
                                <label for="SITE_CELULAR">Celular:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                                    <input type="tel" class="form-control" placeholder="" aria-describedby="SITE_CELULAR" name="SITE_CELULAR" id="SITE_CELULAR" value="<?php echo SITE_CELULAR; ?>" onkeydown="maskTelephone(this, false);"
                                           onkeyup="maskTelephone(this, false);" onblur="maskTelephone(this, true);"/>
                                </div>
                            </div>
                            <br />
                            <div class="col-md-6 input_form">
                                <label for="SITE_CNPJ">CNPJ:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                                    <input type="text" class="form-control cnpj" placeholder="" aria-describedby="SITE_CNPJ" name="SITE_CNPJ" id="SITE_CNPJ" value="<?php echo SITE_CNPJ; ?>">
                                </div>
                            </div>
                            <div class="col-md-6 input_form">
                                <label for="SITE_CRC">CRC:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                                    <input type="text" class="form-control" placeholder="" aria-describedby="SITE_CRC" name="SITE_CRC" id="SITE_CRC" value="<?php echo SITE_CRC; ?>">
                                </div>
                            </div>
                            <br />
                            <div class="col-md-12 col-lg-6 input_form">
                                <label for="SITE_EMAIL">E-mail:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                                    <input type="email" class="form-control" placeholder="" aria-describedby="SITE_EMAIL" name="SITE_EMAIL" id="SITE_EMAIL" value="<?php echo SITE_EMAIL; ?>">
                                </div>
                            </div>
                            <div class="col-md-12 col-lg-6 input_form">
                                <label for="SITE_CERTIDAO_REGULARIDADE">Link Certidão de Regularidade:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-link"></i></span>
                                    <input type="text" class="form-control" placeholder="" aria-describedby="SITE_CERTIDAO_REGULARIDADE" name="SITE_CERTIDAO_REGULARIDADE" id="SITE_CERTIDAO_REGULARIDADE" value="<?php echo SITE_CERTIDAO_REGULARIDADE; ?>">
                                </div>
                                <?php if (SITE_CERTIDAO_REGULARIDADE != "") { ?>
                                    <a href="<?php echo SITE_CERTIDAO_REGULARIDADE ?>" class="btn btn-link" style="padding-left: 0; padding-right: 0;" target="_blank">Veja a Certidão de Regularidade</a>
                                <?php } ?>
                            </div>
                            <div class="col-md-12 col-lg-6">
                                <label for="SITE_ENDERECO">Endereço:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-keyboard-o"></i></span>
                                    <textarea class="form-control" style="height: 100px" name="SITE_ENDERECO" id="SITE_ENDERECO"><?php echo SITE_ENDERECO; ?></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-right">
                                <div class="line-buttons">
                                    <button class="btn btn-success"><i class="fa fa-floppy-o"></i> Salvar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="tab-pane fade in" id="tab_seo">
                    <form name="form_admin" id="form_admin" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="acao" value="alterar"/>
                        <div class="row">
                            <div class="col-lg-6 input_form">
                                <label for="SITE_TITLE">Meta título padrão do site (SEO)</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-keyboard-o" aria-hidden="true"></i></span>
                                    <input class="form-control contador" placeholder="meta título padrão do site" aria-describedby="SITE_TITLE" name="SITE_TITLE" id="SITE_TITLE" value="<?php echo html_entity_decode(SITE_TITLE) ?>">
                                    <span id="count_caracteres" class="input-group-addon" data-total="70"><?php echo(html_entity_decode(SITE_TITLE) == "" ? "70" : 70 - strlen(html_entity_decode(SITE_TITLE))) ?></span>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-6 input_form">
                                <label for="SITE_DESCRIPTION">Meta descrição padrão do site (SEO)</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-keyboard-o" aria-hidden="true"></i></span>
                                    <textarea class="form-control contador" placeholder="meta descricao padrão do site" aria-describedby="SITE_DESCRIPTION" name="SITE_DESCRIPTION" id="SITE_DESCRIPTION" rows="3"><?php echo html_entity_decode(SITE_DESCRIPTION) ?></textarea>
                                    <span id="count_caracteres" class="input-group-addon" data-total="160"><?php echo(html_entity_decode(SITE_DESCRIPTION) == "" ? "160" : 160 - strlen(html_entity_decode(SITE_DESCRIPTION))) ?></span>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-6 input_form">
                                <label for="SITE_KEYWORDS">Meta keywords padrão do site (SEO)</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-keyboard-o" aria-hidden="true"></i></span>
                                    <textarea class="form-control contador" placeholder="meta keywords padrão do site" aria-describedby="SITE_KEYWORDS" name="SITE_KEYWORDS" id="SITE_KEYWORDS" rows="3"><?php echo html_entity_decode(SITE_KEYWORDS) ?></textarea>
                                    <span id="count_caracteres" class="input-group-addon" data-total="160"><?php echo(html_entity_decode(SITE_KEYWORDS) == "" ? "160" : 160 - strlen(html_entity_decode(SITE_KEYWORDS))) ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 text-right">
                                <div class="line-buttons">
                                    <button class="btn btn-success"><i class="fa fa-floppy-o"></i> Salvar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="tab-pane fade in" id="tab_tema">
                    <form name="form_admin" id="form_admin" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="acao" value="alterar"/>
                        <div class="row">
                            <div class="col-lg-6 input_form">
                                <label for="SITE_LOGOTIPO">Logotipo do Cabeçalho: 279px x 75px</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o" aria-hidden="true"></i></span>
                                    <input type="file" class="form-control" placeholder="" aria-describedby="SITE_LOGOTIPO" name="SITE_LOGOTIPO" id="SITE_LOGOTIPO"/>
                                </div>
                                <br>
                                <?php if (SITE_LOGOTIPO) { ?>
                                    <div class="box_imagem_admin imagem-logo">
                                        <img style="max-width: 100%"  src="<?php echo UPLOADS_URL . '/tema/logotipo/' . SITE_LOGOTIPO; ?>" alt="Logotipo" />
                                    </div>
                                <?php } ?>
                            </div>
                            <div class="col-lg-6 input_form">
                                <label for="SITE_LOGOTIPO_RODAPE">Logotipo do Rodapé: 333px x 79px</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o" aria-hidden="true"></i></span>
                                    <input type="file" class="form-control" placeholder="" aria-describedby="SITE_LOGOTIPO_RODAPE" name="SITE_LOGOTIPO_RODAPE" id="SITE_LOGOTIPO_RODAPE"/>
                                </div>
                                <br>
                                <?php if (SITE_LOGOTIPO_RODAPE) { ?>
                                    <div class="box_imagem_admin imagem-logo">
                                        <img style="max-width: 100%"  src="<?php echo UPLOADS_URL . '/tema/logotipo/' . SITE_LOGOTIPO_RODAPE; ?>" alt="Logotipo do rodapé" />
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 text-right">
                                <div class="line-buttons">
                                    <button class="btn btn-success"><i class="fa fa-floppy-o"></i> Salvar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="tab-pane fade in" id="tab_sociais">
                    <form name="form_admin" id="form_admin" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="acao" value="alterar"/>
                        <div class="row">
                            <div class="col-lg-6 input_form">
                                <label for="FACEBOOK"></label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-facebook"></i></span>
                                    <input type="text" class="form-control" placeholder="Facebook" aria-describedby="FACEBOOK" name="FACEBOOK" id="FACEBOOK" value="<?php echo FACEBOOK ?>"/>
                                </div>
                            </div>
                            <div class="col-lg-6 input_form">
                                <label for="INSTAGRAM"></label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-instagram"></i></span>
                                    <input type="text" class="form-control" placeholder="Instagram" aria-describedby="INSTAGRAM" name="INSTAGRAM" id="INSTAGRAM" value="<?php echo INSTAGRAM ?>"/>
                                </div>
                            </div>
                            <div class="col-lg-6 input_form">
                                <label for="YOUTUBE"></label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-youtube"></i></span>
                                    <input type="text" class="form-control" placeholder="Youtube" aria-describedby="YOUTUBE" name="YOUTUBE" id="YOUTUBE" value="<?php echo YOUTUBE ?>"/>
                                </div>
                            </div>
                            <div class="col-lg-6 input_form">
                                <label for="LINKEDIN"></label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-linkedin"></i></span>
                                    <input type="text" class="form-control" placeholder="Linkedin" aria-describedby="LINKEDIN" name="LINKEDIN" id="LINKEDIN" value="<?php echo LINKEDIN ?>"/>
                                </div>
                            </div>
                            <div class="col-lg-6 input_form">
                                <label for="TWITTER"></label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-twitter"></i></span>
                                    <input type="text" class="form-control" placeholder="Linkedin" aria-describedby="TWITTER" name="TWITTER" id="TWITTER" value="<?php echo TWITTER ?>"/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 text-right">
                                <div class="line-buttons">
                                    <button class="btn btn-success"><i class="fa fa-floppy-o"></i> Salvar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('.cnpj').mask('00.000.000/0000-00');

            $(".apagar-imagem").on("click", function () {
                var este = $(this);
                    if (confirm("Deseja realmente apagar esta imagem?")) {
                        $.ajax({
                            url: window.location.href,
                            method: 'post',
                            data: {
                                acao: 'apagar-imagem-header',
                            },
                            dataType: "html",
                            success: function (response) {
                                console.log(response);
                                if (response == 1) {
                                    este.parent().find("img").fadeOut(500);
                                }
                                else {
                                    alert('Houve um problema, tente novamente mais tarde!');
                                }
                            }
                        })
                    }
            });
            if ($('#cp_menu').length > 0) {
                $('#cp_menu').colorpicker();
            }

            //Verifica item selecionado
            $("#tipo_banner option:selected").each(function () {
                $('.tamanho_img span').html($(this).data('width') + 'px X ' + $(this).data('height') + 'px');
            });
            $("#tipo_banner").change(function () {
                $("#tipo_banner option:selected").each(function () {
                    $('.tamanho_img span').html($(this).data('width') + 'px X ' + $(this).data('height') + 'px');
                });
            });

            //Checkbox personalizado
            $('#restricoes_horarios').change(function () {
                if (this.checked) {
                    $('div.horarios_restritos').slideDown();
                } else {
                    $('div.horarios_restritos').slideUp();
                }
            });

            //Confirma a exclusão
            $('[data-toggle=confirmation_delete]').confirmation({
                rootSelector: '[data-toggle=confirmation_delete]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim, Excluir!',
                        onClick: function () {
                            var codigo = $('#id_registro').val();
                            $.ajax({
                                method: "POST",
                                url: "<?php echo $url_formulario ?>",
                                data: {
                                    'acao': 'excluir',
                                    'id': codigo
                                },
                                success: function (retorno) {
                                    if (retorno == 'ok') {
                                        window.location = '<?php echo $url_listagem ?>?del=ok';
                                    }
                                }
                            });
                            return false;
                        }
                    }
                ]
            });
            //Confirma o cancelamento
            $('[data-toggle=confirmation_cancel]').confirmation({
                rootSelector: '[data-toggle=confirmation_cancel]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim',
                        onClick: function () {
                            location.reload();
                        }
                    }
                ]
            });
        });
    </script>
<?php
//Add Footer
include_once('gestao/footer.phtml');