<?php
$page_name = "home";
$page_title = "Página Inicial";
$page_id = 1; // salvar na tabela página para gerar o ID

$obj_config = new Configuracao(true);
$title = "Painel Administrativo";
$str_add_css = array();
$str_add_js = array(/*"chart.min",
      "chart-data"*/);

//BreadCrumb
$breadcrumb = array(array("url" => BASE_ADMIN_URL,
    "nome" => ' Home',
    "icon" => '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'));

//Add Header
include_once('header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <?php
            //Add BreadCrumb
            include_once('breadcrumb.phtml');
            ?>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
        </div>
        <?php
        echo 'Painel administrativo';
        if ((int)getSession("id_perfil", "user") <= 2) {
            ?>
            <div class="liberar_ips">
                <form name="form_liberar_ip" id="form_liberar_ip" method="POST"
                      action="<?php echo BASE_ADMIN_URL . '/home.html' ?>">
                    <input type="hidden" name="acao" id="acao" value="liberar_ip"/>
                    <label>Site está liberado para livre acesso?</label><br/>
                    <input type="radio" name="liberar_acesso" id="liberar_acesso_sim" value="false"
                           <?php if (MANUTENCAO == "false") { ?>checked="checked"<?php } ?> />
                    <label for="liberar_acesso_sim">Sim</label>
                    <input type="radio" name="liberar_acesso" id="liberar_acesso_nao" value="true"
                           <?php if (MANUTENCAO != "false") { ?>checked="checked"<?php } ?> />
                    <label for="liberar_acesso_nao">Não</label>
                    <?php
                    if (MANUTENCAO == "true") {
                        ?>
                        <br/><br/><br/>
                        <label for="liberar_ip">Digite aqui o IP que deseja liberar:</label><br/>
                        <?php
                        //exit(var_dump(strpos(MANUTENCAO_IP, $_SERVER['REMOTE_ADDR'])));
                        if (strpos(MANUTENCAO_IP, $_SERVER['REMOTE_ADDR']) !== false) {
                            ?>
                            <h1>Seu IP já está autorizado!</h1>
                            <?php
                        } else {
                            ?>
                            <input type="text" name="liberar_ip" id="liberar_ip" value=""
                                   placeholder="255.255.255.255"/><br/>
                            <a href="#" class="add_my_ip" id="<?php echo $_SERVER['REMOTE_ADDR'] ?>">Adicionar meu
                                IP</a>
                            <?php
                        }
                    }
                    ?>
                    <br/><br/>
                    <input type="submit" name="salvar" id="salvar" value="Salvar"/>
                </form>
                <?php
                if (MANUTENCAO == "true" && MANUTENCAO_IP != "") {
                    $array_ips = explode(',', MANUTENCAO_IP);
                    if (count($array_ips) > 0) {
                        ?>
                        <p>Relação de IPs autorizados a acessar o site:</p>
                        <ul>
                            <?php
                            foreach ($array_ips as $ip_liberado) {
                                ?>
                                <li><?php echo $ip_liberado ?>
                                    <a href="<?php echo BASE_ADMIN_URL . '/home.html?acao=remover_ip&ip=' . $ip_liberado ?>"><img
                                                src="<?php echo ADMIN_IMAGES_URL . '/icn_delete_img.png' ?>"
                                                width="20"/></a>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>
                        <?php
                    }
                }
                ?>
            </div>
            <?php
        }
        ?>
        <?php if (getRequest('permissao')) { ?>
            <div class="clearfix"></div>
            <br/>
            <div class="alert alert-danger">
                <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Desculpe, você não possui permissão para executar esta determinada função, por favor tente novamente!
            </div>
        <?php } ?>
    </div>
    <script>
        $(document).ready(function () {
            $(".add_my_ip").on("click", function () {
                $("#liberar_ip").val($(this).attr("id"));
            });
        });
    </script>
<?php
//Add Footer
include_once('footer.phtml');
