<?php
$page_name = "tipo_servico_calculadora";
$page_title = "Tipo Serviços Calculadora";
$page_id = 38; // salvar na tabela página para gerar o ID

//URls
$url_listagem = BASE_ADMIN_URL . '/' . $page_name . '-lista.html';
$url_formulario = BASE_ADMIN_URL . '/' . $page_name . '-form.html';

$objeto = new TipoServicoCalculadora(true);

//Informações da Página para BreadCrumb
$pagina = new Pagina();
$pagina->setIdTable($page_id);
$pagina->getByCod();

$grupo = new Pagina();
$grupo->setIdTable($pagina->getIdParent());
$grupo->getByCod();
//End - Informações da Página para BreadCrumb

//Verifica se é alteração ou inclusão para carregar os dados
$id_registro = getRequest("id") ? getRequest("id") : 0;
if ($id_registro > 0) {
    $objeto->setIdTable($id_registro);
    $objeto->getByCod();
    $title = $pagina->getTitulo() . ": " . $id_registro . " | Painel Administrativo";
} else {
    $title = "Novo Registro | Painel Administrativo";
}

//Add JS e CSS
$str_add_css = array('bootstrap-table',
    'switchery',
    'bootstrap-colorpicker.min');
$str_add_js = array('bootstrap-table',
    'switchery',
    'jquery.inputmask.bundle',
    'bootstrap-confirmation.min',
    'bootstrap-colorpicker.min',
    'tipo_servico');

//BreadCrumb
$breadcrumb = array(array("url" => BASE_ADMIN_URL,
    "nome" => ' Home',
    "icon" => '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'),
    array("url" => "#",
        "nome" => ' ' . $grupo->getTitulo(),
        "icon" => '<i class="fa ' . $grupo->getIcone() . '" aria-hidden="true"></i>'),
    array("url" => $url_listagem,
        "nome" => ' Todos ' . $pagina->getTitulo(),
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'),
    array("url" => $url_formulario,
        "nome" => ' ' . $page_title,
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'));

//Add Header
include_once('gestao/header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <?php
            //Add BreadCrumb
            include_once('gestao/breadcrumb.phtml');
            ?>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <a href="<?php echo $url_listagem ?>" class="btn_admin btn btn-default"><i class="fa fa-undo"
                                                                                           aria-hidden="true"></i>
                    Voltar</a>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12">
                <?php
                $retorno = getRequest('msg');
                if ($retorno != "" && $retorno == "ok") {
                    ?>
                    <div class="alert alert-success">
                        <strong><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Ok...</strong> Os dados foram
                        salvos com sucesso!
                    </div>
                    <?php
                } elseif ($retorno != "" && $retorno == "erro") {
                    ?>
                    <div class="alert alert-danger">
                        <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Houve algum
                        problema ao salvar os dados, por favor tente novamente!
                    </div>
                    <?php
                }
                ?>
                <div class="clearfix"></div>
                <form name="form_admin" id="form_admin" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="acao" value="<?php echo $id_registro > 0 ? 'alterar' : 'incluir' ?>"/>
                    <input type="hidden" name="acao_posterior" id="acao_posterior" value=""/>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-xs-12 col-md-2 input_form">
                                    <label for="id_registro">código</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-hashtag" aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" placeholder=""
                                               aria-describedby="id_registro" name="id_registro" id="id_registro"
                                               value="<?php echo $objeto->getIdTable() ?>" readonly="readonly"/>
                                    </div>
                                </div>
                                <div class="col-lg-1 col-md-6 input_form">
                                    <label for="status">status</label>
                                    <div style="position:relative">
                                        <div class="form-group">
                                            <input type="checkbox" id="status" name="status"
                                                   <?php if ($objeto->getStatus() == "A") { ?>checked="checked"<?php } ?>
                                                   class="js-switch flag_form" value="A" data-active="Ativo"
                                                   data-inactive="Inativo"/>
                                            <span class="label_flag"><?php echo $objeto->getStatus() == "A" ? "Ativo" : "Inativo" ?></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-xs-12 col-md-12 input_form">
                                    <label for="nome_tipo_servico_calculadora">nome tipo servico</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control contador" required="required"
                                               data-error="Este campo não pode ficar vázio." placeholder=""
                                               aria-describedby="nome_tipo_servico_calculadora"
                                               name="nome_tipo_servico_calculadora"
                                               id="nome_tipo_servico_calculadora"
                                               value="<?php echo $objeto->getNomeTipoServicoCalculadora() ?>"/>
                                        <span id="count_caracteres" class="input-group-addon"
                                              data-total="150"><?php echo($objeto->getNomeTipoServicoCalculadora() == "" ? "300" : 300 - strlen($objeto->getNomeTipoServicoCalculadora())) ?></span>
                                    </div>
                                </div>
                                <div class="col-xs-3 input_form">
                                    <label for="valor_socio">valor socio</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" required="required"
                                               data-error="Este campo não pode ficar vázio." placeholder=""
                                               aria-describedby="valor_socio"
                                               name="valor_socio"
                                               id="valor_socio"
                                               value="<?php echo number_format($objeto->getValorSocio(),2,',','.') ?>"
                                               onkeyup="somenteNumeros(this);"/>
                                    </div>
                                </div>
                                <?php
                                    //exit(var_dump(($objeto->getValorFuncionario())));
                                ?>
                                <div class="col-xs-3 input_form">
                                    <label for="valor_funcionario">valor funcionario</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" required="required"
                                               data-error="Este campo não pode ficar vázio." placeholder=""
                                               aria-describedby="valor_funcionario"
                                               name="valor_funcionario"
                                               id="valor_funcionario"
                                               value="<?php echo number_format($objeto->getValorFuncionario(),2,',','.') ?>" onkeyup="somenteNumeros(this);"/>
                                    </div>
                                </div>
                                <div class="col-xs-3 input_form">
                                    <label for="maximo_socios">máximo sócios</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" required="required"
                                               data-error="Este campo não pode ficar vázio." placeholder=""
                                               aria-describedby="maximo_socios"
                                               name="maximo_socios"
                                               id="maximo_socios"
                                               value="<?php echo $objeto->getMaximoSocios() ?>"
                                               onkeyup="somenteNumeros(this);"/>
                                    </div>
                                </div>
                                <div class="col-xs-3 input_form">
                                    <label for="maximo_funcionarios">máximo funcionários</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"
                                                                           aria-hidden="true"></i></span>
                                        <input type="text" class="form-control" required="required"
                                               data-error="Este campo não pode ficar vázio." placeholder=""
                                               aria-describedby="maximo_funcionarios"
                                               name="maximo_funcionarios"
                                               id="maximo_funcionarios"
                                               value="<?php echo $objeto->getMaximoFuncionarios() ?>"
                                               onkeyup="somenteNumeros(this);"/>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <?php
                                if ($id_registro > 0){
                                $obj_calculadora_faturamento = new CalculadoraFaturamento();
                                $obj_tipo_servico_calculadora = new TipoServicoCalculadora();
                                $faturamentos = $obj_calculadora_faturamento->listAll('A');
                                $valores_faturamentos = $obj_tipo_servico_calculadora->getValoresFaturamenteByTipoServico($id_registro);
                                ?>
                                <div class="col-xs-12 col-md-12 input_form">
                                    <form id="add_faturamento_valor_tipo_servico">
                                        <label for="id_calculadora_faturamento">Faturamento</label>
                                        <select id="id_calculadora_faturamento" name="id_calculadora_faturamento"
                                                class="form-control">
                                            <?php
                                            foreach ($faturamentos as $faturamento) {
                                                $ja_cadastrado = false;
                                                foreach ($valores_faturamentos as $vf) {
                                                    if ($vf->id_calculadora_faturamento == $faturamento->id_calculadora_faturamento) {
                                                        $ja_cadastrado = true;
                                                        break;
                                                    }
                                                }
                                                if (!$ja_cadastrado) {
                                                    ?>
                                                    <option value="<?php echo $faturamento->id_calculadora_faturamento ?>"><?php echo $faturamento->descricao_faturamento; ?></option>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </select>
                                        <label for="valor">Valor:</label>
                                        <input class="form-control" id="valor" name="valor" type="text"/>
                                        <input class="btn btn-primary" id="add_faturamento_tipo_servico"
                                               name="add_faturamento_tipo_servico" type="button" value="Adicionar" style="display: block;margin: 1% auto;"/>
                                    </form>
                                    <table class="table" id="tabela_tipo_servicos_faturamentos"
                                           name="tabela_tipo_servicos_faturamentos">
                                        <thead>
                                        <tr>
                                            <th>Descricao</th>
                                            <th>Valor</th>
                                            <th>Excluir</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($valores_faturamentos as $vf) {
                                            ?>
                                            <tr>
                                                <td><?php echo $vf->descricao_faturamento ?></td>
                                                <td><?php echo $vf->valor ?></td>
                                                <td data_id_calculadora_faturamento="<?php echo $vf->id_calculadora_faturamento?>">
                                                    <i data_id_tipo_servico_faturamento_calculadora="<?php echo $vf->id_tipo_servico_faturamento_calculadora ?>"
                                                       class="fa fa-trash-o excluir_tipo_servico_faturamento"
                                                       aria-hidden="true"></i></td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <?php
                            }
                            ?>
                        </div>
                    </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-right">
                    <div class="line-buttons">
                        <?php
                        if ($id_registro) {
                            ?>
                            <a href="#" class="btn btn-danger" data-toggle="confirmation_delete"
                               data-title="Excluir Permanetemente?"
                               data-content="Após confirmada está ação não pode ser desfeita!"><i
                                        class="fa fa-trash"></i> Excluir</a>
                            <a href="#" class="btn btn-warning" data-toggle="confirmation_cancel"
                               data-title="Deseja Realmente Cancelar?"
                               data-content="Todas alterações não salvas serão perdidas."><i
                                        class="fa fa-ban"></i> Cancelar</a>
                            <?php
                        }
                        ?>
                        <a href="#" class="btn btn-primary btn_submit_form_new"><i
                                    class="fa fa-floppy-o"></i> Salvar e Adicionar Outro</a>
                        <a href="#" class="btn btn-success btn_submit_form"><i class="fa fa-floppy-o"></i>
                            Salvar</a>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>

    </div>
    <script>
        $(document).ready(function () {

            //Confirma a exclusão
            $('[data-toggle=confirmation_delete]').confirmation({
                rootSelector: '[data-toggle=confirmation_delete]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim, Excluir!',
                        onClick: function () {
                            var codigo = $('#id_registro').val();
                            $.ajax({
                                method: "POST",
                                url: "<?php echo $url_formulario ?>",
                                data: {
                                    'acao': 'excluir',
                                    'id': codigo
                                },
                                success: function (retorno) {
                                    if (retorno == 'ok') {
                                        window.location = '<?php echo $url_listagem ?>?del=ok';
                                    }
                                }
                            });
                            return false;
                        }
                    }
                ]
            });

            //Confirma o cancelamento
            $('[data-toggle=confirmation_cancel]').confirmation({
                rootSelector: '[data-toggle=confirmation_cancel]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim',
                        onClick: function () {
                            location.reload();
                        }
                    }
                ]
            });
        });
        function somenteNumeros(number) {
            var numerosPrmitidos = /[^0-9.,]/;
            numerosPrmitidos.length = 0;
            var valorInput = $(number).val();
            var numero_caracteres = $(number).val().length;
            number.value = "";
            for(var cont=0;cont< numero_caracteres; cont++){
                if (!numerosPrmitidos.test(valorInput[cont])) {
                        number.value += valorInput[cont];
                }
                //console.log(valorInput[cont]);
            }

           /*
            if (numerosPrmitidos.test(valorInput.value)) {
                valorInput.value = "";
            }*/
        }
    </script>
<?php
//Add Footer
include_once('gestao/footer.phtml');