<?php
$page_name = "usuarios";
$page_title = "Manutenção de Usuários";
$page_id = 3; // salvar na tabela página para gerar o ID

//URls
$url_listagem = BASE_ADMIN_URL . '/' . $page_name . '-lista.html';
$url_formulario = BASE_ADMIN_URL . '/' . $page_name . '-form.html';

$objeto = new UsuarioAdmin(true);

//Informações da Página para BreadCrumb
$pagina = new Pagina();
$pagina->setIdTable($page_id);
$pagina->getByCod();

$grupo = new Pagina();
$grupo->setIdTable($pagina->getIdParent());
$grupo->getByCod();
//End - Informações da Página para BreadCrumb

//Verifica se é alteração ou inclusão para carregar os dados
$id_registro = getRequest("id") ? getRequest("id") : 0;
if ($id_registro > 0) {
    $objeto->setIdTable($id_registro);
    $objeto->getByCod();
    $title = $pagina->getTitulo() . ": " . $id_registro . " | Painel Administrativo";
} else {
    $title = "Novo Registro | Painel Administrativo";
}

//Add JS e CSS
$str_add_css = array(
    'bootstrap-table',
    'switchery'
);
$str_add_js = array(
    'bootstrap-table',
    'switchery',
    'jquery.inputmask.bundle',
    'bootstrap-confirmation.min'
);

//BreadCrumb
$breadcrumb = array(
    array(
        "url" => BASE_ADMIN_URL,
        "nome" => ' Home',
        "icon" => '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'
    ),
    array(
        "url" => "#",
        "nome" => ' ' . $grupo->getTitulo(),
        "icon" => '<i class="fa ' . $grupo->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_listagem,
        "nome" => ' Todos ' . $pagina->getTitulo(),
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_formulario,
        "nome" => ' ' . $page_title,
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    )
);

//Add Header
include_once('gestao/header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <?php
            //Add BreadCrumb
            include_once('gestao/breadcrumb.phtml');
            ?>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <a href="<?php echo $url_listagem ?>" class="btn_admin btn btn-default"><i class="fa fa-undo" aria-hidden="true"></i> Voltar</a>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12">
                <?php
                $retorno = getRequest('msg');
                if ($retorno != "" && $retorno == "ok") {
                    ?>
                    <div class="alert alert-success">
                        <strong><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Ok...</strong> Os dados foram salvos com sucesso!
                    </div>
                <?php
                } elseif ($retorno != "" && $retorno == "erro") {
                    ?>
                    <div class="alert alert-danger">
                        <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Houve algum problema ao salvar os dados, por favor tente novamente!
                    </div>
                <?php
                }
                ?>
                <div class="clearfix"></div>
                <div class="tabs">
                    <ul class="nav nav-pills">
                        <li class="active"><a href="#tab_dados_usuario" data-toggle="tab">Dados do Usuário</a></li>
                        <?php
                        if ($objeto->getAcessosRestritos() != "") {
                            ?>
                            <li>
                                <a href="#tab_tentativas_proibidas" data-toggle="tab"><span style="color:#F00;"><?php if (!$objeto->getIdUsuarioCiente()) { ?>
                                            <i class="fa fa-exclamation-triangle" aria-hidden="true"></i><?php } ?></span> Registros de Tentativas de Acessos Proibidos</a>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab_dados_usuario">
                            <form name="form_admin" id="form_admin" method="post">
                                <input type="hidden" name="acao" value="<?php echo $id_registro > 0 ? 'alterar' : 'incluir' ?>"/>
                                <input type="hidden" name="acao_posterior" id="acao_posterior" value=""/>

                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="row">
                                            <div class="col-lg-2 col-md-6 col-xs-12 input_form">
                                                <label for="id_registro">código</label>

                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="fa fa-hashtag" aria-hidden="true"></i></span>
                                                    <input type="text" class="form-control" placeholder="" aria-describedby="id_registro" name="id_registro" id="id_registro" value="<?php echo $objeto->getIdTable() ?>" readonly="readonly"/>
                                                </div>
                                            </div>
                                            <div class="col-lg-3 col-md-6 col-xs-12 input_form">
                                                <label for="data_cadastro">data cadastro</label>

                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                                                    <input type="text" class="form-control" placeholder="" aria-describedby="data_cadastro" name="data_cadastro" id="data_cadastro" value="<?php echo $objeto->getDataCadastro() ?>" readonly="readonly"/>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-6 col-xs-12 input_form">
                                                <label for="id_perfil">perfil</label>

                                                <select class="form-control" aria-describedby="id_perfil" name="id_perfil" id="id_perfil" required="required" data-error="Selecione o perfil do usuário">
                                                    <option value="">Selecione o perfil</option>
                                                    <?php
                                                    $perfil = new Perfil();
                                                    $lista_perfis = $perfil->getPerfisDisponiveis();
                                                    if ($lista_perfis !== false && $id_registro != 1) {
                                                        foreach ($lista_perfis as $dados_perfil) {
                                                            ?>
                                                            <option value="<?php echo $dados_perfil->id_perfil ?>" <?php if ($dados_perfil->id_perfil == $objeto->getIdPerfil()) { ?>selected="selected"<?php } ?>><?php echo $dados_perfil->nome ?></option>
                                                        <?php }
                                                    } elseif ($id_registro == 1) {
                                                        ?>
                                                        <option value="1" selected="selected">Super Administrador</option>
                                                    <?php
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="col-xs-12 col-md-6 input_form">
                                                <label for="nome_completo">nome</label>

                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="fa fa-align-left" aria-hidden="true"></i></span>
                                                    <input type="text" class="form-control" placeholder="" aria-describedby="nome_completo" name="nome_completo" id="nome_completo" value="<?php echo $objeto->getNomeCompleto() ?>" required="required" data-error="Preencha este campo corretamente"/>
                                                </div>
                                            </div>
                                            <div class="col-xs-12 col-md-6 input_form">
                                                <label for="email">email</label>

                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="fa fa-envelope-o" aria-hidden="true"></i></span>
                                                    <input type="text" class="form-control" placeholder="" aria-describedby="email" name="email" id="email" value="<?php echo $objeto->getEmail() ?>" required="required" data-error="Preencha este campo corretamente"/>
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="col-xs-12 col-md-3 input_form">
                                                <label for="login">login</label>

                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="fa fa-lock" aria-hidden="true"></i></span>
                                                    <input type="text" class="form-control" placeholder="" aria-describedby="login" name="login" id="login" value="<?php echo $objeto->getLogin() ?>" required="required" data-error="Preencha este campo corretamente"/>
                                                </div>
                                            </div>
                                            <div class="col-xs-12 col-md-3 input_form">
                                                <label for="senha">senha</label>

                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>
                                                    <input type="text" class="form-control" placeholder="" aria-describedby="senha" name="senha" id="senha" value="" <?php if ($id_registro <= 0) { ?>required="required" data-error="Preencha este campo corretamente"<?php } ?> />
                                                </div>
                                            </div>
                                            <?php
                                            if ($id_registro > 0) {
                                                ?>
                                                <div class="col-lg-3 col-md-6 col-sm-8 input_form">
                                                    <label for="ultimo_acesso">último acesso</label>

                                                    <div class="input-group">
                                                        <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                                                        <input type="text" class="form-control" placeholder="" aria-describedby="ultimo_acesso" name="ultimo_acesso" id="ultimo_acesso" value="<?php echo $objeto->getUltimoAcesso() ?>" readonly="readonly"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-3 col-md-6 col-sm-8 input_form">
                                                    <label for="qtde_acessos">quantidade acessos</label>

                                                    <div class="input-group">
                                                        <span class="input-group-addon"><i class="fa fa-hashtag" aria-hidden="true"></i></span>
                                                        <input type="text" class="form-control" placeholder="" aria-describedby="qtde_acessos" name="qtde_acessos" id="qtde_acessos" value="<?php echo $objeto->getQtdeAcessos() ?>" readonly="readonly"/>
                                                    </div>
                                                </div>
                                            <?php
                                            }
                                            ?>
                                            <div class="clearfix"></div>
                                            <div class="col-xs-6 col-md-4 input_form">
                                                <label for="status">status</label>

                                                <div style="position:relative">
                                                    <div class="form-group">
                                                        <input type="checkbox" id="status" name="status" <?php if ($objeto->getStatus() == "A") { ?>checked="checked"<?php } ?> class="js-switch flag_form" value="A" data-active="Ativo" data-inactive="Inativo"/>
                                                        <span class="label_flag"><?php echo $objeto->getStatus() == "A" ? "Ativo" : "Inativo" ?></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xs-6 col-md-4 input_form">
                                                <label for="restricoes_horarios">possui restrição de horários?</label>

                                                <div style="position:relative">
                                                    <div class="form-group">
                                                        <input type="checkbox" id="restricoes_horarios" name="restricoes_horarios" <?php if ($objeto->getRestricoesHorarios() == "S") { ?>checked="checked"<?php } ?> class="js-switch flag_form" value="S" data-active="Sim" data-inactive="Não"/>
                                                        <span class="label_flag"><?php echo $objeto->getRestricoesHorarios() == "S" ? "Sim" : "Não" ?></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="horarios_restritos" <?php if ($objeto->getRestricoesHorarios() == "N") { ?>style="display:none"<?php } ?>>
                                                <div class="col-lg-6 input_form">
                                                    <fieldset>
                                                        <legend>Dias da Semana Permitidos</legend>
                                                        <?php
                                                        $dias_permitidos = explode(";", $objeto->getDiasAutorizados());
                                                        ?>
                                                        <ul class="dias_semana">
                                                            <li>
                                                                <input type="checkbox" id="dia_semana_1" name="dia_semana[1]" value="S" <?php if (isset($dias_permitidos[1]) && $dias_permitidos[1] == 'S') { ?>checked="checked"<?php } ?> />
                                                                <label for="dia_semana_1">Segunda-feira</label></li>
                                                            <li>
                                                                <input type="checkbox" id="dia_semana_2" name="dia_semana[2]" value="S" <?php if (isset($dias_permitidos[2]) && $dias_permitidos[2] == 'S') { ?>checked="checked"<?php } ?> />
                                                                <label for="dia_semana_2">Terça-feira</label></li>
                                                            <li>
                                                                <input type="checkbox" id="dia_semana_3" name="dia_semana[3]" value="S" <?php if (isset($dias_permitidos[3]) && $dias_permitidos[3] == 'S') { ?>checked="checked"<?php } ?> />
                                                                <label for="dia_semana_3">Quarta-feira</label></li>
                                                            <li>
                                                                <input type="checkbox" id="dia_semana_4" name="dia_semana[4]" value="S" <?php if (isset($dias_permitidos[4]) && $dias_permitidos[4] == 'S') { ?>checked="checked"<?php } ?> />
                                                                <label for="dia_semana_4">Quinta-feira</label></li>
                                                            <li>
                                                                <input type="checkbox" id="dia_semana_5" name="dia_semana[5]" value="S" <?php if (isset($dias_permitidos[5]) && $dias_permitidos[5] == 'S') { ?>checked="checked"<?php } ?> />
                                                                <label for="dia_semana_5">Sexta-feira</label></li>
                                                            <li>
                                                                <input type="checkbox" id="dia_semana_6" name="dia_semana[6]" value="S" <?php if (isset($dias_permitidos[6]) && $dias_permitidos[6] == 'S') { ?>checked="checked"<?php } ?> />
                                                                <label for="dia_semana_6">Sábado</label></li>
                                                            <li>
                                                                <input type="checkbox" id="dia_semana_0" name="dia_semana[0]" value="S" <?php if (isset($dias_permitidos[0]) && $dias_permitidos[0] == 'S') { ?>checked="checked"<?php } ?> />
                                                                <label for="dia_semana_0">Domingo</label></li>
                                                        </ul>
                                                    </fieldset>
                                                </div>
                                                <div class="col-lg-6 input_form">
                                                    <fieldset>
                                                        <legend>Horários Permitidos</legend>
                                                        <?php
                                                        $horas_permitidas = explode(";", $objeto->getHorariosAutorizados());
                                                        ?>
                                                        <div class="row">
                                                            <div class="col-lg-3 input_form">
                                                                <label for="entrada">entrada</label>

                                                                <div class="input-group">
                                                                    <span class="input-group-addon" id="entrada"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
                                                                    <input type="text" class="form-control mask_time" placeholder="" aria-describedby="entrada" name="entrada" id="entrada" value="<?php echo isset($horas_permitidas[0]) ? $horas_permitidas[0] : "" ?>"/>
                                                                </div>
                                                            </div>
                                                            <div class="col-lg-3 input_form">
                                                                <label for="saida_intervalo" title="Saída para o Intervalo">saída int.</label>

                                                                <div class="input-group">
                                                                    <span class="input-group-addon" id="entrada"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
                                                                    <input type="text" class="form-control mask_time" placeholder="" aria-describedby="saida_intervalo" name="saida_intervalo" id="saida_intervalo" value="<?php echo isset($horas_permitidas[1]) ? $horas_permitidas[1] : "" ?>"/>
                                                                </div>
                                                            </div>
                                                            <div class="col-lg-3 input_form">
                                                                <label for="entrada_intervalo" title="Rotorno do Intervalo">entrada int.</label>

                                                                <div class="input-group">
                                                                    <span class="input-group-addon" id="entrada"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
                                                                    <input type="text" class="form-control mask_time" placeholder="" aria-describedby="entrada_intervalo" name="entrada_intervalo" id="entrada_intervalo" value="<?php echo isset($horas_permitidas[2]) ? $horas_permitidas[2] : "" ?>"/>
                                                                </div>
                                                            </div>
                                                            <div class="col-lg-3 input_form">
                                                                <label for="saida">saída</label>

                                                                <div class="input-group">
                                                                    <span class="input-group-addon" id="saida"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
                                                                    <input type="text" class="form-control mask_time" placeholder="" aria-describedby="saida" name="saida" id="saida" value="<?php echo isset($horas_permitidas[3]) ? $horas_permitidas[3] : "" ?>"/>
                                                                </div>
                                                            </div>
                                                            <div class="clearfix"></div>
                                                        </div>
                                                    </fieldset>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12 text-right">
                                        <div class="line-buttons">
                                            <?php
                                            if ($id_registro) {
                                                ?>
                                                <a href="#" class="btn btn-danger" data-toggle="confirmation_delete" data-title="Excluir Permanetemente?" data-content="Após confirmada está ação não pode ser desfeita!"><i class="fa fa-trash"></i> Excluir</a>
                                                <a href="#" class="btn btn-warning" data-toggle="confirmation_cancel" data-title="Deseja Realmente Cancelar?" data-content="Todas alterações não salvas serão perdidas."><i class="fa fa-ban"></i> Cancelar</a>
                                                <?php
                                            }
                                            ?>
                                            <a href="#" class="btn btn-primary btn_submit_form_new"><i class="fa fa-floppy-o"></i> Salvar e Adicionar Outro</a>
                                            <a href="#" class="btn btn-success btn_submit_form"><i class="fa fa-floppy-o"></i> Salvar</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <?php if ($objeto->getAcessosRestritos() != "") { ?>
                            <div class="tab-pane fade" id="tab_tentativas_proibidas">
                                <h4><strong>Registros de Tentativas de Acessos Proibidos</strong></h4><br/>
                                <?php echo $objeto->getAcessosRestritos(); ?>
                                <?php if (!$objeto->getIdUsuarioCiente()) { ?>
                                    <form action="" method="post">
                                        <input type="hidden" name="acao" value="setCiente"/>
                                        <input type="hidden" name="id_usuario" value="<?php echo $id_registro ?>"/>
                                        <input type="hidden" name="id_ciente" value="<?php echo getSession('id_usuario', 'info_user') ?>"/>
                                        <?php
                                        if (Perfil::verificaPermissao(getSession("id_perfil", "info_user"), $page_id, 'alterar')) {
                                            ?>
                                            <button class="btn btn-success">
                                                <i class="fa fa-check-square-o"></i> Estou ciente
                                            </button>
                                            <?php
                                        }
                                        ?>
                                    </form>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <script>
        $(document).ready(function () {
            $('.mask_time').inputmask("99:99"); //mask hora

            //Checkbox personalizado
            $('#restricoes_horarios').change(function () {
                if (this.checked) {
                    $('div.horarios_restritos').slideDown();
                } else {
                    $('div.horarios_restritos').slideUp();
                }
            });

            //Confirma a exclusão
            $('[data-toggle=confirmation_delete]').confirmation({
                rootSelector: '[data-toggle=confirmation_delete]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim, Excluir!',
                        onClick: function () {
                            var codigo = $('#id_registro').val();
                            $.ajax({
                                method: "POST",
                                url: "<?php echo $url_formulario ?>",
                                data: {
                                    'acao': 'excluir',
                                    'id': codigo
                                },
                                success: function (retorno) {
                                    console.log()
                                    if (retorno == 'ok') {
                                        window.location = '<?php echo $url_listagem ?>?del=ok';
                                    }
                                },
                                error: function (err) {
                                }
                            });
                            return false;
                        }
                    }
                ]
            });


            //Confirma o cancelamento
            $('[data-toggle=confirmation_cancel]').confirmation({
                rootSelector: '[data-toggle=confirmation_cancel]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim',
                        onClick: function () {
                            location.reload();
                        }
                    }
                ]
            });
        });
    </script>
<?php
//Add Footer
include_once('gestao/footer.phtml');