      </div>
    </section>
  </div>
  <footer>
    <div id="footer">
      <div class="box_footer">
        <p class="developer">Innovare Company &copy;<?php echo date('Y') ?> - Todos os Direitos Reservados<br />Telefones: (16) 3402-1199 | (16) 3025-0677</p>
        <a href="http://www.innovarecompany.com.br" target="_blank" class="developer">www.innovarecompany.com.br</a>
      </div>
    </div>  
  </footer>
</body>
</html>