<?php
$page_name = "artigos";
$page_title = "Artigos";
$page_id = 20; // salvar na tabela página para gerar o ID

//URls
$url_listagem = BASE_ADMIN_URL . '/' . $page_name . '-lista.html';
$url_formulario = BASE_ADMIN_URL . '/' . $page_name . '-form.html';

$objeto = new Artigo(true);

//Informações da Página para BreadCrumb
$pagina = new Pagina();
$pagina->setIdTable($page_id);
$pagina->getByCod();

$grupo = new Pagina();
$grupo->setIdTable($pagina->getIdParent());
$grupo->getByCod();
//End - Informações da Página para BreadCrumb

//Verifica se é alteração ou inclusão para carregar os dados
$id_registro = getRequest("id") ? getRequest("id") : 0;
if ($id_registro > 0) {
    $objeto->setIdTable($id_registro);
    $objeto->getByCod();
    $title = $pagina->getTitulo() . ": " . $id_registro . " | Painel Administrativo";
} else {
    $title = "Novo Registro | Painel Administrativo";
}

//Add JS e CSS
$str_add_css = array(
    'bootstrap-table',
    'switchery',
    'bootstrap-colorpicker.min',
);
$str_add_js = array(
    'bootstrap-table',
    'switchery',
    'tinymce2/tinymce.min',
    'bootstrap-confirmation.min',
    'bootstrap-colorpicker.min'
);

//BreadCrumb
$breadcrumb = array(
    array(
        "url" => BASE_ADMIN_URL,
        "nome" => ' Home',
        "icon" => '<i class="fas fa-home fontawesome"></i>'
    ),
    array(
        "url" => "#",
        "nome" => ' ' . $grupo->getTitulo(),
        "icon" => '<i class="fa ' . $grupo->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_listagem,
        "nome" => ' Todos ' . $pagina->getTitulo(),
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    ),
    array(
        "url" => $url_formulario,
        "nome" => ' ' . $page_title,
        "icon" => '<i class="fa ' . $pagina->getIcone() . '" aria-hidden="true"></i>'
    )
);

//Add Header
include_once('gestao/header.phtml');
?>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <?php
            //Add BreadCrumb
            include_once('gestao/breadcrumb.phtml');
            ?>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h1 class="page-header"><?php echo $page_title ?></h1>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <a href="<?php echo $url_listagem ?>" class="btn_admin btn btn-default">
                    <i class="fa fa-undo" aria-hidden="true"></i>
                    Voltar
                </a>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12">
                <?php
                $retorno = getRequest('msg');
                if ($retorno != "" && $retorno == "ok") {
                    ?>
                    <div class="alert alert-success">
                        <strong><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Ok...</strong> Os dados foram
                        salvos com sucesso!
                    </div>
                    <?php
                } elseif ($retorno != "" && $retorno == "erro") {
                    ?>
                    <div class="alert alert-danger">
                        <strong><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Falha...</strong> Houve algum
                        problema ao salvar os dados, por favor tente novamente!
                    </div>
                    <?php
                }
                ?>
                <div class="clearfix"></div>
                <?php
                $retorno = getRequest('msg');
                ?>
                <form name="form_admin" id="form_admin" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="acao" value="<?php echo $id_registro > 0 ? 'alterar' : 'incluir' ?>" />
                    <input type="hidden" name="acao_posterior" id="acao_posterior" value="" />
                    <div class="row">
                        <div class="col-md-3 col-lg-2 input_form">
                            <label for="id_registro">Código</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-hashtag" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" placeholder=""
                                       aria-describedby="id_registro" name="id_registro" id="id_registro"
                                       value="<?php echo $objeto->getIdTable() ?>" readonly="readonly"/>
                            </div>
                        </div>
                        <?php if ($id_registro) { ?>
                            <div class="col-md-4 col-lg-3 input_form">
                                <label for="datahora_cadastro">Data/Hora do Cadastro</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-calendar-o"></i></span>
                                    <input type="text" class="form-control" placeholder="Data/Hora Cadastro"
                                           name="datahora_cadastro" id="datahora_cadastro" readonly="readonly"
                                           value="<?php echo $objeto->getDatahoraCadastro() ?>" />
                                </div>
                            </div>
                        <?php } ?>
                        <div class="col-md-3 col-lg-2 input_form">
                            <label for="status">Status</label>
                            <div style="position:relative">
                                <div class="form-group">
                                    <input type="checkbox" id="status" name="status"
                                           <?php if ($objeto->getStatus() == "A" || $id_registro == '') { ?>checked="checked"<?php } ?>
                                           class="js-switch flag_form" value="A" data-active="Ativo"
                                           data-inactive="Inativo"/>
                                    <span class="label_flag"><?php echo $objeto->getStatus() == "A" || $id_registro == '' ? "Ativo" : "Inativo" ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                        <div class="col-xs-12 col-lg-6">
                            <div class="row">
                                <div class="col-xs-12 col-lg-12 input_form">
                                    <label for="titulo">Título do Artigo</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"></i></span>
                                        <input type="text" class="form-control" placeholder="Título do artigo"
                                               name="titulo" id="titulo" required="required"
                                               value="<?php echo $objeto->getTitulo() ?>" />
                                    </div>
                                </div>
                                <div class="col-xs-12 col-lg-12 input_form">
                                    <label for="descricao">Descrição do Artigo</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-align-left"></i></span>
                                        <textarea class="form-control" rows="3"
                                                  placeholder="Descrição da artigo"
                                                  name="descricao" id="descricao"
                                                  required="required"><?php echo $objeto->getDescricao() ?></textarea>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-lg-12 input_form">
                                    <label for="data_artigo">Data do Artigo</label>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="fa fa-calendar" aria-hidden="true"></i>
                                        </span>
                                        <input type="date" class="form-control"
                                               name="data_artigo" id="data_artigo"
                                               value="<?php echo formatarData('bd', $objeto->getDataArtigo()) ?>"
                                               required="required"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-lg-6">
                            <div class="row">
                                <div class="col-lg-12 input_form">
                                    <label for="meta_titulo">Meta Título da Página (SEO)</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-keyboard-o" aria-hidden="true"></i></span>
                                        <input class="form-control contador" placeholder="Meta Título da Página" name="meta_titulo" id="meta_titulo" value="<?php echo html_entity_decode($objeto->getMetaTitulo()) ?>">
                                        <span id="count_caracteres" class="input-group-addon" data-total="70"><?php echo(html_entity_decode($objeto->getMetaTitulo()) == "" ? "70" : 70 - strlen(html_entity_decode($objeto->getMetaTitulo()))) ?></span>
                                    </div>
                                </div>
                                <div class="col-lg-12 input_form">
                                    <label for="meta_descricao">Meta Descrição da Página (SEO)</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-keyboard-o" aria-hidden="true"></i></span>
                                        <textarea class="form-control contador" placeholder="Meta Descrição da Página" name="meta_descricao" id="meta_descricao" rows="3"><?php echo html_entity_decode($objeto->getMetaDescricao()) ?></textarea>
                                        <span id="count_caracteres" class="input-group-addon" data-total="160"><?php echo(html_entity_decode($objeto->getMetaDescricao()) == "" ? "160" : 160 - strlen(html_entity_decode($objeto->getMetaDescricao()))) ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 input_form">
                            <label for="conteudo">Conteúdo do Artigo</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-align-left"></i></span>
                                <textarea id="conteudo" name="conteudo" class="form-control tinymce"
                                          required="required"><?php echo $objeto->getConteudo()?></textarea>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <br/>
                        <br/>

                        <div class="col-lg-6 input_form">
                            <strong>Imagem da Página do Artigo</strong>
                            <br>
                            <label for="url_imagem">Imagem [JPG]: 768px x 276px em 72 dpi</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                <input type="file" class="form-control" placeholder=""
                                       name="url_imagem" id="url_imagem"/>
                            </div>
                            <?php if ($objeto->getUrlImagem()) { ?>
                                <small>A imagem atual será excluida após substituí-la por outra.</small>
                                <div class="box_url_banner_topo">
                                    <img style="max-width: 100%;" src="<?php echo UPLOADS_URL . '/artigos/' . $objeto->getUrlImagem() ?>"
                                         alt="" class="imagem_bg"/>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="col-lg-6">
                            <strong>Imagem de Capa do Artigo</strong>
                            <br>
                            <label for="url_imagem_capa">Imagem [JPG]: 370px x 240px em 72 dpi</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                <input type="file" class="form-control" placeholder=""
                                       name="url_imagem_capa" id="url_imagem_capa"
                                       <?php if (!$objeto->getUrlImagemCapa()) { ?>required="required"<?php } ?> />
                            </div>
                            <?php if ($objeto->getUrlImagemCapa()) { ?>
                                <small>A imagem atual será excluida após substituí-la por outra.</small>
                                <div class="box_url_imagem_destaque">
                                    <img style="max-width: 100%;" src="<?php echo UPLOADS_URL . '/artigos/' . $objeto->getUrlImagemCapa() ?>"
                                         alt="" class="imagem_bg"/>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 text-right">
                            <div class="line-buttons">
                                <?php if ($id_registro) { ?>
                                    <a href="#" class="btn btn-danger"
                                       data-toggle="confirmation_delete"
                                       data-title="Excluir Permanetemente?"
                                       data-content="Após confirmada está ação não pode ser desfeita!"><i
                                            class="fa fa-trash"></i> Excluir</a>
                                    <a href="#" class="btn btn-warning"
                                       data-toggle="confirmation_cancel"
                                       data-title="Deseja Realmente Cancelar?"
                                       data-content="Todas alterações não salvas serão perdidas.">
                                        <i class="fa fa-ban"></i> Cancelar</a>
                                <?php } ?>
                                <a href="#" class="btn btn-primary btn_submit_form_new">
                                    <i class="fa fa-floppy-o"></i> Salvar e Adicionar Outro</a>
                                <a href="#" class="btn btn-success btn_submit_form">
                                    <i class="fa fa-floppy-o"></i> Salvar</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            // Confirma a exclusão
            $('[data-toggle=confirmation_delete]').confirmation({
                rootSelector: '[data-toggle=confirmation_delete]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim, Excluir!',
                        onClick: function () {
                            var codigo = $('#id_registro').val();
                            $.ajax({
                                method: "POST",
                                url: "<?php echo $url_formulario ?>",
                                data: {
                                    'acao': 'excluir',
                                    'id': codigo
                                },
                                success: function (retorno) {
                                    if (retorno == 'ok') {
                                        window.location = '<?php echo $url_listagem ?>?del=ok';
                                    }
                                }
                            });
                            return false;
                        }
                    }
                ]
            });

            // Confirma o cancelamento
            $('[data-toggle=confirmation_cancel]').confirmation({
                rootSelector: '[data-toggle=confirmation_cancel]',
                buttons: [
                    {
                        class: 'btn btn-primary',
                        icon: 'glyphicon glyphicon-remove',
                        label: 'Não',
                        onClick: function () {
                            return false;
                        }
                    },
                    {
                        class: 'btn btn-danger',
                        icon: 'glyphicon glyphicon-ok',
                        label: 'Sim',
                        onClick: function () {
                            location.reload();
                        }
                    }
                ]
            });
        });
    </script>
<?php
//Add Footer
include_once('gestao/footer.phtml');