<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no"/>
    <meta name="theme-color" content="#64a175">
    <meta name="author" content="3dots"/>
    <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE"/>
    <title><?php echo SITE_TITLE ?></title>
    <meta name="description" content="<?php echo SITE_DESCRIPTION ?>"/>
    <meta name="keywords" content="<?php echo SITE_KEYWORDS ?>"/>
    <link href='<?php echo BASE_IMAGES_URL ?>/favicon.ico' rel='shortcut' type='image/x-icon'/>
    <link href='<?php echo BASE_IMAGES_URL ?>/favicon.png' rel='icon' type='image/png'/>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_CSS_URL ?>/fonts.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_CSS_URL ?>/foundation.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_CSS_URL ?>/style.css"/>
</head>
<body id="manutencao" class="position_center">
<div class="row fullContainer" id="manutencao">
    <div class="medium-10 large-10 columns medium-centered large-centered text-center">
        <div class="fullWidth">
            <img class="max-width" src="<?php echo BASE_IMAGES_URL ?>/manutencao.png" alt="Manutenção">
        </div>
    </div>
</div>
</body>
</html>