<?php
$page = "migrar-empresa";

// ID 3 = Migrar Minha Empresa
$id_institucional = 3;

$objInstitucional = new Institucional();
$objInstitucional->setIdTable($id_institucional);
$objInstitucional->getByCod();

$str_add_css = array("institucional");

include_once("header.phtml");
?>
<main class="page-institutional">
    <?php if ($objInstitucional->url_banner_topo != "") { ?>
    <section class="banner">
        <picture>
            <img src="<?php echo UPLOADS_URL . '/institucionais/banners/' . $objInstitucional->url_banner_topo ?>" class="img-fluid" alt="<?php echo $objInstitucional->titulo ?>">
        </picture>
    </section>
    <?php } ?>
    <nav aria-label="breadcrumb">
        <div class="container container-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo BASE_SITE_URL ?>">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page"><?php echo $objInstitucional->titulo ?></li>
            </ol>
        </div>
    </nav>
    <section class="institutional overflow-hidden">
        <div class="container">
            <h3 class="section-title section-underline" data-aos="fade-up" data-aos-delay="300" data-aos-duration="700"><?php echo $objInstitucional->titulo ?></h3>
            <div class="content" data-aos="fade-up" data-aos-delay="500" data-aos-duration="700">
                <?php echo $objInstitucional->conteudo ?>
            </div>
            <?php if (SITE_CELULAR) { ?>
            <a href="https://wa.me/+55<?php echo $whatsapp ?>" target="_blank" class="btn btn-green" data-aos="fade-up" data-aos-delay="500" data-aos-duration="700">Quero migrar minha empresa</a>
            <?php } ?>
        </div>
    </section>
</main>
<?php
$str_add_js = array();

include_once("footer.phtml");
?>
