<?php
$page = "sobre";

$banner = new Banner();
$bannerQuemSomos = $banner->getBannersByTipo('A', 3, 'posicao');

$quemSomos = new QuemSomos();
$quemSomos->setIdTable(1);
$quemSomos->getByCod();

$servico = new Servico();
$servicosDestaques = $servico->getServicosDestaques('S', 'A');

$str_add_css = array("sobre");

include_once("header.phtml");
?>
<main class="page-about">
    <?php if ($bannerQuemSomos) { ?>
    <section class="banner">
        <picture>
            <img src="<?php echo UPLOADS_URL . '/banners/' . $bannerQuemSomos[0]->url_imagem ?>" class="img-fluid" alt="<?php echo $bannerQuemSomos[0]->nome_banner ?>">
        </picture>
    </section>
    <?php } ?>
    <nav aria-label="breadcrumb">
        <div class="container container-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo BASE_SITE_URL ?>">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page"><?php echo $quemSomos->nome_pagina ?></li>
            </ol>
        </div>
    </nav>
    <div class="container">
        <h3 class="section-title section-underline" data-aos="fade-up" data-aos-delay="300" data-aos-duration="700"><?php echo $quemSomos->nome_pagina ?></h3>
    </div>
    <section class="about overflow-hidden">
        <div class="container">
            <div class="row align-items-lg-center">
                <div class="col-lg-6 px-xl-5" data-aos="fade-up" data-aos-delay="400" data-aos-duration="700">
                    <h2 class="title section-underline"><?php echo $quemSomos->titulo_sobre ?></h2>
                    <div class="description">
                        <span><?php echo $quemSomos->descricao_sobre ?></span>
                    </div>
                </div>
                <div class="col-lg-6 px-xl-5" data-aos="fade-up" data-aos-delay="600" data-aos-duration="700">
                    <div class="image">
                        <img src="<?php echo UPLOADS_URL . '/quem-somos/' . $quemSomos->url_imagem_sobre ?>" class="img-fluid" alt="<?php echo $quemSomos->titulo_sobre ?>">
                    </div>
                </div>
            </div>
            <?php if ($quemSomos->titulo_nosso_diferencial != "" && $quemSomos->descricao_nosso_diferencial != "" && $quemSomos->url_imagem_nosso_diferencial != "") { ?>
            <div class="row align-items-lg-center">
                <div class="col-lg-6 px-xl-5 order-lg-1" data-aos="fade-up" data-aos-delay="400" data-aos-duration="700">
                    <h2 class="title section-underline"><?php echo $quemSomos->titulo_nosso_diferencial ?></h2>
                    <div class="description">
                        <span><?php echo $quemSomos->descricao_nosso_diferencial ?></span>
                    </div>
                </div>
                <div class="col-lg-6 px-xl-5 order-lg-0" data-aos="fade-up" data-aos-delay="600" data-aos-duration="700">
                    <div class="image">
                        <img src="<?php echo UPLOADS_URL . '/quem-somos/' . $quemSomos->url_imagem_nosso_diferencial ?>" class="img-fluid" alt="<?php echo $quemSomos->titulo_nosso_diferencial ?>">
                    </div>
                </div>
            </div>
            <?php } if ($quemSomos->titulo_como_funciona != "" && $quemSomos->descricao_como_funciona != "" && $quemSomos->url_imagem_como_funciona != "") { ?>
            <div class="row align-items-lg-center">
                <div class="col-lg-6 px-xl-5" data-aos="fade-up" data-aos-delay="400" data-aos-duration="700">
                    <h2 class="title section-underline"><?php echo $quemSomos->titulo_como_funciona ?></h2>
                    <div class="description">
                        <span><?php echo $quemSomos->descricao_como_funciona ?></span>
                    </div>
                </div>
                <div class="col-lg-6 px-xl-5" data-aos="fade-up" data-aos-delay="600" data-aos-duration="700">
                    <div class="image">
                        <img src="<?php echo UPLOADS_URL . '/quem-somos/' . $quemSomos->url_imagem_como_funciona ?>" class="img-fluid" alt="<?php echo $quemSomos->titulo_como_funciona ?>">
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>
    </section>
    <?php if ($servicosDestaques) { ?>
    <section class="our-services overflow-hidden">
        <div class="container">
            <h2 class="section-title" data-aos="fade-up" data-aos-delay="300" data-aos-duration="700">Conheça a Contabilidade Online para pessoa física e jurídica de pequeno e médio porte</h2>
            <h5 class="section-subtitle section-underline" data-aos="fade-up" data-aos-delay="400" data-aos-duration="700">Somos uma contabilidade completa que une experiência, confiabilidade, inovação, baixo custo e tecnologia ao seu alcance.</h5>
            <div class="content" data-aos="fade-up" data-aos-delay="500" data-aos-duration="700">
                <div class="card-group">
                    <?php foreach ($servicosDestaques as $infoServicoDestaque) { ?>
                    <div class="card mb-0">
                        <a href="<?php echo BASE_SITE_URL . '/servico/' . $infoServicoDestaque->url_rewrite ?>" class="stretched-link"></a>
                        <img src="<?php echo UPLOADS_URL . '/servicos/icones/' . $infoServicoDestaque->url_icone ?>" class="img-fluid" alt="<?php echo $infoServicoDestaque->titulo ?>">
                        <div class="card-title mb-2">
                            <h4><?php echo $infoServicoDestaque->titulo ?></h4>
                        </div>
                        <div class="card-description">
                            <span><?php echo $infoServicoDestaque->subtitulo ?></span>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <?php if (SITE_CELULAR) { ?>
            <a href="https://wa.me/+55<?php echo $whatsapp ?>" target="_blank" class="btn btn-green" data-aos="fade-up" data-aos-delay="500" data-aos-duration="700">Contratar agora</a>
            <?php } ?>
        </div>
    </section>
    <?php } ?>
</main>
<?php
$str_add_js = array();

include_once("footer.phtml");
?>
